// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionPlanUpdate is the builder for updating SubscriptionPlan entities.
type SubscriptionPlanUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionPlanMutation
}

// Where appends a list predicates to the SubscriptionPlanUpdate builder.
func (_u *SubscriptionPlanUpdate) Where(ps ...predicate.SubscriptionPlan) *SubscriptionPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionPlanUpdate) SetGroupID(v int64) *SubscriptionPlanUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableGroupID(v *int64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionPlanUpdate) AddGroupID(v int64) *SubscriptionPlanUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SubscriptionPlanUpdate) SetName(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableName(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SubscriptionPlanUpdate) SetDescription(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableDescription(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanUpdate) SetPrice(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillablePrice(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanUpdate) AddPrice(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *SubscriptionPlanUpdate) SetOriginalPrice(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableOriginalPrice(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *SubscriptionPlanUpdate) AddOriginalPrice(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *SubscriptionPlanUpdate) ClearOriginalPrice() *SubscriptionPlanUpdate {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetRenewalDiscountPercent sets the "renewal_discount_percent" field.
func (_u *SubscriptionPlanUpdate) SetRenewalDiscountPercent(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetRenewalDiscountPercent()
	_u.mutation.SetRenewalDiscountPercent(v)
	return _u
}

// SetNillableRenewalDiscountPercent sets the "renewal_discount_percent" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableRenewalDiscountPercent(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetRenewalDiscountPercent(*v)
	}
	return _u
}

// AddRenewalDiscountPercent adds value to the "renewal_discount_percent" field.
func (_u *SubscriptionPlanUpdate) AddRenewalDiscountPercent(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddRenewalDiscountPercent(v)
	return _u
}

// ClearRenewalDiscountPercent clears the value of the "renewal_discount_percent" field.
func (_u *SubscriptionPlanUpdate) ClearRenewalDiscountPercent() *SubscriptionPlanUpdate {
	_u.mutation.ClearRenewalDiscountPercent()
	return _u
}

// SetFiveHourLimitUsd sets the "five_hour_limit_usd" field.
func (_u *SubscriptionPlanUpdate) SetFiveHourLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetFiveHourLimitUsd()
	_u.mutation.SetFiveHourLimitUsd(v)
	return _u
}

// SetNillableFiveHourLimitUsd sets the "five_hour_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableFiveHourLimitUsd(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetFiveHourLimitUsd(*v)
	}
	return _u
}

// AddFiveHourLimitUsd adds value to the "five_hour_limit_usd" field.
func (_u *SubscriptionPlanUpdate) AddFiveHourLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddFiveHourLimitUsd(v)
	return _u
}

// ClearFiveHourLimitUsd clears the value of the "five_hour_limit_usd" field.
func (_u *SubscriptionPlanUpdate) ClearFiveHourLimitUsd() *SubscriptionPlanUpdate {
	_u.mutation.ClearFiveHourLimitUsd()
	return _u
}

// SetSevenDayLimitUsd sets the "seven_day_limit_usd" field.
func (_u *SubscriptionPlanUpdate) SetSevenDayLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetSevenDayLimitUsd()
	_u.mutation.SetSevenDayLimitUsd(v)
	return _u
}

// SetNillableSevenDayLimitUsd sets the "seven_day_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableSevenDayLimitUsd(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetSevenDayLimitUsd(*v)
	}
	return _u
}

// AddSevenDayLimitUsd adds value to the "seven_day_limit_usd" field.
func (_u *SubscriptionPlanUpdate) AddSevenDayLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddSevenDayLimitUsd(v)
	return _u
}

// ClearSevenDayLimitUsd clears the value of the "seven_day_limit_usd" field.
func (_u *SubscriptionPlanUpdate) ClearSevenDayLimitUsd() *SubscriptionPlanUpdate {
	_u.mutation.ClearSevenDayLimitUsd()
	return _u
}

// SetThirtyDayLimitUsd sets the "thirty_day_limit_usd" field.
func (_u *SubscriptionPlanUpdate) SetThirtyDayLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetThirtyDayLimitUsd()
	_u.mutation.SetThirtyDayLimitUsd(v)
	return _u
}

// SetNillableThirtyDayLimitUsd sets the "thirty_day_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableThirtyDayLimitUsd(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetThirtyDayLimitUsd(*v)
	}
	return _u
}

// AddThirtyDayLimitUsd adds value to the "thirty_day_limit_usd" field.
func (_u *SubscriptionPlanUpdate) AddThirtyDayLimitUsd(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddThirtyDayLimitUsd(v)
	return _u
}

// ClearThirtyDayLimitUsd clears the value of the "thirty_day_limit_usd" field.
func (_u *SubscriptionPlanUpdate) ClearThirtyDayLimitUsd() *SubscriptionPlanUpdate {
	_u.mutation.ClearThirtyDayLimitUsd()
	return _u
}

// SetStock sets the "stock" field.
func (_u *SubscriptionPlanUpdate) SetStock(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetStock()
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableStock(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// AddStock adds value to the "stock" field.
func (_u *SubscriptionPlanUpdate) AddStock(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddStock(v)
	return _u
}

// ClearStock clears the value of the "stock" field.
func (_u *SubscriptionPlanUpdate) ClearStock() *SubscriptionPlanUpdate {
	_u.mutation.ClearStock()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionPlanUpdate) SetCurrency(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableCurrency(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *SubscriptionPlanUpdate) SetValidityDays(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableValidityDays(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *SubscriptionPlanUpdate) AddValidityDays(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetValidityUnit sets the "validity_unit" field.
func (_u *SubscriptionPlanUpdate) SetValidityUnit(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetValidityUnit(v)
	return _u
}

// SetNillableValidityUnit sets the "validity_unit" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableValidityUnit(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetValidityUnit(*v)
	}
	return _u
}

// SetFeatures sets the "features" field.
func (_u *SubscriptionPlanUpdate) SetFeatures(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableFeatures(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *SubscriptionPlanUpdate) SetProductName(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableProductName(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *SubscriptionPlanUpdate) SetForSale(v bool) *SubscriptionPlanUpdate {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableForSale(v *bool) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubscriptionPlanUpdate) SetSortOrder(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableSortOrder(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubscriptionPlanUpdate) AddSortOrder(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPlanUpdate) SetUpdatedAt(v time.Time) *SubscriptionPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *SubscriptionPlanUpdate) AddRedeemCodeIDs(ids ...int64) *SubscriptionPlanUpdate {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanUpdate) AddRedeemCodes(v ...*RedeemCode) *SubscriptionPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// AddUserSubscriptionIDs adds the "user_subscriptions" edge to the UserSubscription entity by IDs.
func (_u *SubscriptionPlanUpdate) AddUserSubscriptionIDs(ids ...int64) *SubscriptionPlanUpdate {
	_u.mutation.AddUserSubscriptionIDs(ids...)
	return _u
}

// AddUserSubscriptions adds the "user_subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanUpdate) AddUserSubscriptions(v ...*UserSubscription) *SubscriptionPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserSubscriptionIDs(ids...)
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_u *SubscriptionPlanUpdate) Mutation() *SubscriptionPlanMutation {
	return _u.mutation
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanUpdate) ClearRedeemCodes() *SubscriptionPlanUpdate {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *SubscriptionPlanUpdate) RemoveRedeemCodeIDs(ids ...int64) *SubscriptionPlanUpdate {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *SubscriptionPlanUpdate) RemoveRedeemCodes(v ...*RedeemCode) *SubscriptionPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// ClearUserSubscriptions clears all "user_subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanUpdate) ClearUserSubscriptions() *SubscriptionPlanUpdate {
	_u.mutation.ClearUserSubscriptions()
	return _u
}

// RemoveUserSubscriptionIDs removes the "user_subscriptions" edge to UserSubscription entities by IDs.
func (_u *SubscriptionPlanUpdate) RemoveUserSubscriptionIDs(ids ...int64) *SubscriptionPlanUpdate {
	_u.mutation.RemoveUserSubscriptionIDs(ids...)
	return _u
}

// RemoveUserSubscriptions removes "user_subscriptions" edges to UserSubscription entities.
func (_u *SubscriptionPlanUpdate) RemoveUserSubscriptions(v ...*UserSubscription) *SubscriptionPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserSubscriptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subscriptionplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RenewalDiscountPercent(); ok {
		if err := subscriptionplan.RenewalDiscountPercentValidator(v); err != nil {
			return &ValidationError{Name: "renewal_discount_percent", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.renewal_discount_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FiveHourLimitUsd(); ok {
		if err := subscriptionplan.FiveHourLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "five_hour_limit_usd", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.five_hour_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SevenDayLimitUsd(); ok {
		if err := subscriptionplan.SevenDayLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "seven_day_limit_usd", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.seven_day_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThirtyDayLimitUsd(); ok {
		if err := subscriptionplan.ThirtyDayLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "thirty_day_limit_usd", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.thirty_day_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stock(); ok {
		if err := subscriptionplan.StockValidator(v); err != nil {
			return &ValidationError{Name: "stock", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.stock": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := subscriptionplan.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidityUnit(); ok {
		if err := subscriptionplan.ValidityUnitValidator(v); err != nil {
			return &ValidationError{Name: "validity_unit", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.validity_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := subscriptionplan.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.product_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionplan.Table, subscriptionplan.Columns, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionplan.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionplan.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subscriptionplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(subscriptionplan.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(subscriptionplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(subscriptionplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(subscriptionplan.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RenewalDiscountPercent(); ok {
		_spec.SetField(subscriptionplan.FieldRenewalDiscountPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRenewalDiscountPercent(); ok {
		_spec.AddField(subscriptionplan.FieldRenewalDiscountPercent, field.TypeFloat64, value)
	}
	if _u.mutation.RenewalDiscountPercentCleared() {
		_spec.ClearField(subscriptionplan.FieldRenewalDiscountPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FiveHourLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldFiveHourLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFiveHourLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldFiveHourLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.FiveHourLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldFiveHourLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SevenDayLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldSevenDayLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSevenDayLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldSevenDayLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.SevenDayLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldSevenDayLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ThirtyDayLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldThirtyDayLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedThirtyDayLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldThirtyDayLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.ThirtyDayLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldThirtyDayLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(subscriptionplan.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStock(); ok {
		_spec.AddField(subscriptionplan.FieldStock, field.TypeInt, value)
	}
	if _u.mutation.StockCleared() {
		_spec.ClearField(subscriptionplan.FieldStock, field.TypeInt)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscriptionplan.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(subscriptionplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityUnit(); ok {
		_spec.SetField(subscriptionplan.FieldValidityUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(subscriptionplan.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(subscriptionplan.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(subscriptionplan.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.UserSubscriptionsTable,
			Columns: []string{subscriptionplan.UserSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.UserSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.UserSubscriptionsTable,
			Columns: []string{subscriptionplan.UserSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.UserSubscriptionsTable,
			Columns: []string{subscriptionplan.UserSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPlanUpdateOne is the builder for updating a single SubscriptionPlan entity.
type SubscriptionPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionPlanMutation
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionPlanUpdateOne) SetGroupID(v int64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableGroupID(v *int64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionPlanUpdateOne) AddGroupID(v int64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *SubscriptionPlanUpdateOne) SetName(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableName(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SubscriptionPlanUpdateOne) SetDescription(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableDescription(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanUpdateOne) SetPrice(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillablePrice(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanUpdateOne) AddPrice(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *SubscriptionPlanUpdateOne) SetOriginalPrice(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableOriginalPrice(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *SubscriptionPlanUpdateOne) AddOriginalPrice(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *SubscriptionPlanUpdateOne) ClearOriginalPrice() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetRenewalDiscountPercent sets the "renewal_discount_percent" field.
func (_u *SubscriptionPlanUpdateOne) SetRenewalDiscountPercent(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetRenewalDiscountPercent()
	_u.mutation.SetRenewalDiscountPercent(v)
	return _u
}

// SetNillableRenewalDiscountPercent sets the "renewal_discount_percent" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableRenewalDiscountPercent(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetRenewalDiscountPercent(*v)
	}
	return _u
}

// AddRenewalDiscountPercent adds value to the "renewal_discount_percent" field.
func (_u *SubscriptionPlanUpdateOne) AddRenewalDiscountPercent(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddRenewalDiscountPercent(v)
	return _u
}

// ClearRenewalDiscountPercent clears the value of the "renewal_discount_percent" field.
func (_u *SubscriptionPlanUpdateOne) ClearRenewalDiscountPercent() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearRenewalDiscountPercent()
	return _u
}

// SetFiveHourLimitUsd sets the "five_hour_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) SetFiveHourLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetFiveHourLimitUsd()
	_u.mutation.SetFiveHourLimitUsd(v)
	return _u
}

// SetNillableFiveHourLimitUsd sets the "five_hour_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableFiveHourLimitUsd(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetFiveHourLimitUsd(*v)
	}
	return _u
}

// AddFiveHourLimitUsd adds value to the "five_hour_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) AddFiveHourLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddFiveHourLimitUsd(v)
	return _u
}

// ClearFiveHourLimitUsd clears the value of the "five_hour_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) ClearFiveHourLimitUsd() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearFiveHourLimitUsd()
	return _u
}

// SetSevenDayLimitUsd sets the "seven_day_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) SetSevenDayLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetSevenDayLimitUsd()
	_u.mutation.SetSevenDayLimitUsd(v)
	return _u
}

// SetNillableSevenDayLimitUsd sets the "seven_day_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableSevenDayLimitUsd(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetSevenDayLimitUsd(*v)
	}
	return _u
}

// AddSevenDayLimitUsd adds value to the "seven_day_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) AddSevenDayLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddSevenDayLimitUsd(v)
	return _u
}

// ClearSevenDayLimitUsd clears the value of the "seven_day_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) ClearSevenDayLimitUsd() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearSevenDayLimitUsd()
	return _u
}

// SetThirtyDayLimitUsd sets the "thirty_day_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) SetThirtyDayLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetThirtyDayLimitUsd()
	_u.mutation.SetThirtyDayLimitUsd(v)
	return _u
}

// SetNillableThirtyDayLimitUsd sets the "thirty_day_limit_usd" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableThirtyDayLimitUsd(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetThirtyDayLimitUsd(*v)
	}
	return _u
}

// AddThirtyDayLimitUsd adds value to the "thirty_day_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) AddThirtyDayLimitUsd(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddThirtyDayLimitUsd(v)
	return _u
}

// ClearThirtyDayLimitUsd clears the value of the "thirty_day_limit_usd" field.
func (_u *SubscriptionPlanUpdateOne) ClearThirtyDayLimitUsd() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearThirtyDayLimitUsd()
	return _u
}

// SetStock sets the "stock" field.
func (_u *SubscriptionPlanUpdateOne) SetStock(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetStock()
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableStock(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// AddStock adds value to the "stock" field.
func (_u *SubscriptionPlanUpdateOne) AddStock(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddStock(v)
	return _u
}

// ClearStock clears the value of the "stock" field.
func (_u *SubscriptionPlanUpdateOne) ClearStock() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearStock()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionPlanUpdateOne) SetCurrency(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableCurrency(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *SubscriptionPlanUpdateOne) SetValidityDays(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableValidityDays(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *SubscriptionPlanUpdateOne) AddValidityDays(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetValidityUnit sets the "validity_unit" field.
func (_u *SubscriptionPlanUpdateOne) SetValidityUnit(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetValidityUnit(v)
	return _u
}

// SetNillableValidityUnit sets the "validity_unit" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableValidityUnit(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetValidityUnit(*v)
	}
	return _u
}

// SetFeatures sets the "features" field.
func (_u *SubscriptionPlanUpdateOne) SetFeatures(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableFeatures(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *SubscriptionPlanUpdateOne) SetProductName(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableProductName(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *SubscriptionPlanUpdateOne) SetForSale(v bool) *SubscriptionPlanUpdateOne {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableForSale(v *bool) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *SubscriptionPlanUpdateOne) SetSortOrder(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableSortOrder(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *SubscriptionPlanUpdateOne) AddSortOrder(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPlanUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_u *SubscriptionPlanUpdateOne) AddRedeemCodeIDs(ids ...int64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddRedeemCodeIDs(ids...)
	return _u
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanUpdateOne) AddRedeemCodes(v ...*RedeemCode) *SubscriptionPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedeemCodeIDs(ids...)
}

// AddUserSubscriptionIDs adds the "user_subscriptions" edge to the UserSubscription entity by IDs.
func (_u *SubscriptionPlanUpdateOne) AddUserSubscriptionIDs(ids ...int64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddUserSubscriptionIDs(ids...)
	return _u
}

// AddUserSubscriptions adds the "user_subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanUpdateOne) AddUserSubscriptions(v ...*UserSubscription) *SubscriptionPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserSubscriptionIDs(ids...)
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_u *SubscriptionPlanUpdateOne) Mutation() *SubscriptionPlanMutation {
	return _u.mutation
}

// ClearRedeemCodes clears all "redeem_codes" edges to the RedeemCode entity.
func (_u *SubscriptionPlanUpdateOne) ClearRedeemCodes() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearRedeemCodes()
	return _u
}

// RemoveRedeemCodeIDs removes the "redeem_codes" edge to RedeemCode entities by IDs.
func (_u *SubscriptionPlanUpdateOne) RemoveRedeemCodeIDs(ids ...int64) *SubscriptionPlanUpdateOne {
	_u.mutation.RemoveRedeemCodeIDs(ids...)
	return _u
}

// RemoveRedeemCodes removes "redeem_codes" edges to RedeemCode entities.
func (_u *SubscriptionPlanUpdateOne) RemoveRedeemCodes(v ...*RedeemCode) *SubscriptionPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedeemCodeIDs(ids...)
}

// ClearUserSubscriptions clears all "user_subscriptions" edges to the UserSubscription entity.
func (_u *SubscriptionPlanUpdateOne) ClearUserSubscriptions() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearUserSubscriptions()
	return _u
}

// RemoveUserSubscriptionIDs removes the "user_subscriptions" edge to UserSubscription entities by IDs.
func (_u *SubscriptionPlanUpdateOne) RemoveUserSubscriptionIDs(ids ...int64) *SubscriptionPlanUpdateOne {
	_u.mutation.RemoveUserSubscriptionIDs(ids...)
	return _u
}

// RemoveUserSubscriptions removes "user_subscriptions" edges to UserSubscription entities.
func (_u *SubscriptionPlanUpdateOne) RemoveUserSubscriptions(v ...*UserSubscription) *SubscriptionPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserSubscriptionIDs(ids...)
}

// Where appends a list predicates to the SubscriptionPlanUpdate builder.
func (_u *SubscriptionPlanUpdateOne) Where(ps ...predicate.SubscriptionPlan) *SubscriptionPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPlanUpdateOne) Select(field string, fields ...string) *SubscriptionPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPlan entity.
func (_u *SubscriptionPlanUpdateOne) Save(ctx context.Context) (*SubscriptionPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanUpdateOne) SaveX(ctx context.Context) *SubscriptionPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subscriptionplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RenewalDiscountPercent(); ok {
		if err := subscriptionplan.RenewalDiscountPercentValidator(v); err != nil {
			return &ValidationError{Name: "renewal_discount_percent", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.renewal_discount_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FiveHourLimitUsd(); ok {
		if err := subscriptionplan.FiveHourLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "five_hour_limit_usd", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.five_hour_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SevenDayLimitUsd(); ok {
		if err := subscriptionplan.SevenDayLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "seven_day_limit_usd", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.seven_day_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThirtyDayLimitUsd(); ok {
		if err := subscriptionplan.ThirtyDayLimitUsdValidator(v); err != nil {
			return &ValidationError{Name: "thirty_day_limit_usd", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.thirty_day_limit_usd": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Stock(); ok {
		if err := subscriptionplan.StockValidator(v); err != nil {
			return &ValidationError{Name: "stock", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.stock": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := subscriptionplan.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidityUnit(); ok {
		if err := subscriptionplan.ValidityUnitValidator(v); err != nil {
			return &ValidationError{Name: "validity_unit", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.validity_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := subscriptionplan.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPlan.product_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionPlanUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionplan.Table, subscriptionplan.Columns, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionplan.FieldID)
		for _, f := range fields {
			if !subscriptionplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptionplan.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptionplan.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subscriptionplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(subscriptionplan.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(subscriptionplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(subscriptionplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(subscriptionplan.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RenewalDiscountPercent(); ok {
		_spec.SetField(subscriptionplan.FieldRenewalDiscountPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRenewalDiscountPercent(); ok {
		_spec.AddField(subscriptionplan.FieldRenewalDiscountPercent, field.TypeFloat64, value)
	}
	if _u.mutation.RenewalDiscountPercentCleared() {
		_spec.ClearField(subscriptionplan.FieldRenewalDiscountPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FiveHourLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldFiveHourLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFiveHourLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldFiveHourLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.FiveHourLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldFiveHourLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SevenDayLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldSevenDayLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSevenDayLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldSevenDayLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.SevenDayLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldSevenDayLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ThirtyDayLimitUsd(); ok {
		_spec.SetField(subscriptionplan.FieldThirtyDayLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedThirtyDayLimitUsd(); ok {
		_spec.AddField(subscriptionplan.FieldThirtyDayLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.ThirtyDayLimitUsdCleared() {
		_spec.ClearField(subscriptionplan.FieldThirtyDayLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(subscriptionplan.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStock(); ok {
		_spec.AddField(subscriptionplan.FieldStock, field.TypeInt, value)
	}
	if _u.mutation.StockCleared() {
		_spec.ClearField(subscriptionplan.FieldStock, field.TypeInt)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscriptionplan.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(subscriptionplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(subscriptionplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityUnit(); ok {
		_spec.SetField(subscriptionplan.FieldValidityUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(subscriptionplan.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(subscriptionplan.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(subscriptionplan.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedeemCodesIDs(); len(nodes) > 0 && !_u.mutation.RedeemCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.RedeemCodesTable,
			Columns: []string{subscriptionplan.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.UserSubscriptionsTable,
			Columns: []string{subscriptionplan.UserSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.UserSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.UserSubscriptionsTable,
			Columns: []string{subscriptionplan.UserSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.UserSubscriptionsTable,
			Columns: []string{subscriptionplan.UserSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
