// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// Ticket is the model entity for the Ticket schema.
type Ticket struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TicketNo holds the value of the "ticket_no" field.
	TicketNo string `json:"ticket_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// RequesterEmail holds the value of the "requester_email" field.
	RequesterEmail string `json:"requester_email,omitempty"`
	// RequesterUsername holds the value of the "requester_username" field.
	RequesterUsername string `json:"requester_username,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Impact holds the value of the "impact" field.
	Impact string `json:"impact,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AssigneeID holds the value of the "assignee_id" field.
	AssigneeID *int64 `json:"assignee_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// APIKeyName holds the value of the "api_key_name" field.
	APIKeyName string `json:"api_key_name,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID *int64 `json:"payment_order_id,omitempty"`
	// PaymentOrderNo holds the value of the "payment_order_no" field.
	PaymentOrderNo string `json:"payment_order_no,omitempty"`
	// UserSubscriptionID holds the value of the "user_subscription_id" field.
	UserSubscriptionID *int64 `json:"user_subscription_id,omitempty"`
	// SubscriptionName holds the value of the "subscription_name" field.
	SubscriptionName string `json:"subscription_name,omitempty"`
	// LastPublicMessageAt holds the value of the "last_public_message_at" field.
	LastPublicMessageAt time.Time `json:"last_public_message_at,omitempty"`
	// LastActivityAt holds the value of the "last_activity_at" field.
	LastActivityAt time.Time `json:"last_activity_at,omitempty"`
	// ActionRequiredSince holds the value of the "action_required_since" field.
	ActionRequiredSince *time.Time `json:"action_required_since,omitempty"`
	// UserNotificationSeq holds the value of the "user_notification_seq" field.
	UserNotificationSeq int64 `json:"user_notification_seq,omitempty"`
	// UserLastReadSeq holds the value of the "user_last_read_seq" field.
	UserLastReadSeq int64 `json:"user_last_read_seq,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// ReopenDeadline holds the value of the "reopen_deadline" field.
	ReopenDeadline *time.Time `json:"reopen_deadline,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketQuery when eager-loading is set.
	Edges        TicketEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketEdges holds the relations/edges for other nodes in the graph.
type TicketEdges struct {
	// Requester holds the value of the requester edge.
	Requester *User `json:"requester,omitempty"`
	// Assignee holds the value of the assignee edge.
	Assignee *User `json:"assignee,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*TicketMessage `json:"messages,omitempty"`
	// Events holds the value of the events edge.
	Events []*TicketEvent `json:"events,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*TicketAttachment `json:"attachments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// RequesterOrErr returns the Requester value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) RequesterOrErr() (*User, error) {
	if e.Requester != nil {
		return e.Requester, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "requester"}
}

// AssigneeOrErr returns the Assignee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) AssigneeOrErr() (*User, error) {
	if e.Assignee != nil {
		return e.Assignee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assignee"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) MessagesOrErr() ([]*TicketMessage, error) {
	if e.loadedTypes[2] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) EventsOrErr() ([]*TicketEvent, error) {
	if e.loadedTypes[3] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) AttachmentsOrErr() ([]*TicketAttachment, error) {
	if e.loadedTypes[4] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ticket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticket.FieldID, ticket.FieldUserID, ticket.FieldAssigneeID, ticket.FieldUsageLogID, ticket.FieldAPIKeyID, ticket.FieldPaymentOrderID, ticket.FieldUserSubscriptionID, ticket.FieldUserNotificationSeq, ticket.FieldUserLastReadSeq, ticket.FieldVersion:
			values[i] = new(sql.NullInt64)
		case ticket.FieldTicketNo, ticket.FieldRequesterEmail, ticket.FieldRequesterUsername, ticket.FieldSubject, ticket.FieldCategory, ticket.FieldImpact, ticket.FieldPriority, ticket.FieldStatus, ticket.FieldRequestID, ticket.FieldAPIKeyName, ticket.FieldPaymentOrderNo, ticket.FieldSubscriptionName:
			values[i] = new(sql.NullString)
		case ticket.FieldCreatedAt, ticket.FieldUpdatedAt, ticket.FieldLastPublicMessageAt, ticket.FieldLastActivityAt, ticket.FieldActionRequiredSince, ticket.FieldResolvedAt, ticket.FieldReopenDeadline, ticket.FieldClosedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ticket fields.
func (_m *Ticket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticket.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ticket.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ticket.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ticket.FieldTicketNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_no", values[i])
			} else if value.Valid {
				_m.TicketNo = value.String
			}
		case ticket.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case ticket.FieldRequesterEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requester_email", values[i])
			} else if value.Valid {
				_m.RequesterEmail = value.String
			}
		case ticket.FieldRequesterUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requester_username", values[i])
			} else if value.Valid {
				_m.RequesterUsername = value.String
			}
		case ticket.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case ticket.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case ticket.FieldImpact:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field impact", values[i])
			} else if value.Valid {
				_m.Impact = value.String
			}
		case ticket.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case ticket.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ticket.FieldAssigneeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assignee_id", values[i])
			} else if value.Valid {
				_m.AssigneeID = new(int64)
				*_m.AssigneeID = value.Int64
			}
		case ticket.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case ticket.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case ticket.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case ticket.FieldAPIKeyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_name", values[i])
			} else if value.Valid {
				_m.APIKeyName = value.String
			}
		case ticket.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int64)
				*_m.PaymentOrderID = value.Int64
			}
		case ticket.FieldPaymentOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_no", values[i])
			} else if value.Valid {
				_m.PaymentOrderNo = value.String
			}
		case ticket.FieldUserSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_subscription_id", values[i])
			} else if value.Valid {
				_m.UserSubscriptionID = new(int64)
				*_m.UserSubscriptionID = value.Int64
			}
		case ticket.FieldSubscriptionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_name", values[i])
			} else if value.Valid {
				_m.SubscriptionName = value.String
			}
		case ticket.FieldLastPublicMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_public_message_at", values[i])
			} else if value.Valid {
				_m.LastPublicMessageAt = value.Time
			}
		case ticket.FieldLastActivityAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_activity_at", values[i])
			} else if value.Valid {
				_m.LastActivityAt = value.Time
			}
		case ticket.FieldActionRequiredSince:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field action_required_since", values[i])
			} else if value.Valid {
				_m.ActionRequiredSince = new(time.Time)
				*_m.ActionRequiredSince = value.Time
			}
		case ticket.FieldUserNotificationSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_notification_seq", values[i])
			} else if value.Valid {
				_m.UserNotificationSeq = value.Int64
			}
		case ticket.FieldUserLastReadSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_last_read_seq", values[i])
			} else if value.Valid {
				_m.UserLastReadSeq = value.Int64
			}
		case ticket.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case ticket.FieldReopenDeadline:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reopen_deadline", values[i])
			} else if value.Valid {
				_m.ReopenDeadline = new(time.Time)
				*_m.ReopenDeadline = value.Time
			}
		case ticket.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case ticket.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ticket.
// This includes values selected through modifiers, order, etc.
func (_m *Ticket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequester queries the "requester" edge of the Ticket entity.
func (_m *Ticket) QueryRequester() *UserQuery {
	return NewTicketClient(_m.config).QueryRequester(_m)
}

// QueryAssignee queries the "assignee" edge of the Ticket entity.
func (_m *Ticket) QueryAssignee() *UserQuery {
	return NewTicketClient(_m.config).QueryAssignee(_m)
}

// QueryMessages queries the "messages" edge of the Ticket entity.
func (_m *Ticket) QueryMessages() *TicketMessageQuery {
	return NewTicketClient(_m.config).QueryMessages(_m)
}

// QueryEvents queries the "events" edge of the Ticket entity.
func (_m *Ticket) QueryEvents() *TicketEventQuery {
	return NewTicketClient(_m.config).QueryEvents(_m)
}

// QueryAttachments queries the "attachments" edge of the Ticket entity.
func (_m *Ticket) QueryAttachments() *TicketAttachmentQuery {
	return NewTicketClient(_m.config).QueryAttachments(_m)
}

// Update returns a builder for updating this Ticket.
// Note that you need to call Ticket.Unwrap() before calling this method if this Ticket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ticket) Update() *TicketUpdateOne {
	return NewTicketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ticket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ticket) Unwrap() *Ticket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ticket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ticket) String() string {
	var builder strings.Builder
	builder.WriteString("Ticket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ticket_no=")
	builder.WriteString(_m.TicketNo)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("requester_email=")
	builder.WriteString(_m.RequesterEmail)
	builder.WriteString(", ")
	builder.WriteString("requester_username=")
	builder.WriteString(_m.RequesterUsername)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("impact=")
	builder.WriteString(_m.Impact)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.AssigneeID; v != nil {
		builder.WriteString("assignee_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("api_key_name=")
	builder.WriteString(_m.APIKeyName)
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("payment_order_no=")
	builder.WriteString(_m.PaymentOrderNo)
	builder.WriteString(", ")
	if v := _m.UserSubscriptionID; v != nil {
		builder.WriteString("user_subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("subscription_name=")
	builder.WriteString(_m.SubscriptionName)
	builder.WriteString(", ")
	builder.WriteString("last_public_message_at=")
	builder.WriteString(_m.LastPublicMessageAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_activity_at=")
	builder.WriteString(_m.LastActivityAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ActionRequiredSince; v != nil {
		builder.WriteString("action_required_since=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_notification_seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserNotificationSeq))
	builder.WriteString(", ")
	builder.WriteString("user_last_read_seq=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserLastReadSeq))
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReopenDeadline; v != nil {
		builder.WriteString("reopen_deadline=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// Tickets is a parsable slice of Ticket.
type Tickets []*Ticket
