// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketAttachmentCreate is the builder for creating a TicketAttachment entity.
type TicketAttachmentCreate struct {
	config
	mutation *TicketAttachmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUploadToken sets the "upload_token" field.
func (_c *TicketAttachmentCreate) SetUploadToken(v string) *TicketAttachmentCreate {
	_c.mutation.SetUploadToken(v)
	return _c
}

// SetUploadedBy sets the "uploaded_by" field.
func (_c *TicketAttachmentCreate) SetUploadedBy(v int64) *TicketAttachmentCreate {
	_c.mutation.SetUploadedBy(v)
	return _c
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableUploadedBy(v *int64) *TicketAttachmentCreate {
	if v != nil {
		_c.SetUploadedBy(*v)
	}
	return _c
}

// SetUploaderRole sets the "uploader_role" field.
func (_c *TicketAttachmentCreate) SetUploaderRole(v string) *TicketAttachmentCreate {
	_c.mutation.SetUploaderRole(v)
	return _c
}

// SetTicketID sets the "ticket_id" field.
func (_c *TicketAttachmentCreate) SetTicketID(v int64) *TicketAttachmentCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableTicketID(v *int64) *TicketAttachmentCreate {
	if v != nil {
		_c.SetTicketID(*v)
	}
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *TicketAttachmentCreate) SetMessageID(v int64) *TicketAttachmentCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableMessageID(v *int64) *TicketAttachmentCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *TicketAttachmentCreate) SetState(v string) *TicketAttachmentCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableState(v *string) *TicketAttachmentCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetStorageProvider sets the "storage_provider" field.
func (_c *TicketAttachmentCreate) SetStorageProvider(v string) *TicketAttachmentCreate {
	_c.mutation.SetStorageProvider(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *TicketAttachmentCreate) SetObjectKey(v string) *TicketAttachmentCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetOriginalName sets the "original_name" field.
func (_c *TicketAttachmentCreate) SetOriginalName(v string) *TicketAttachmentCreate {
	_c.mutation.SetOriginalName(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *TicketAttachmentCreate) SetContentType(v string) *TicketAttachmentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetByteSize sets the "byte_size" field.
func (_c *TicketAttachmentCreate) SetByteSize(v int64) *TicketAttachmentCreate {
	_c.mutation.SetByteSize(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *TicketAttachmentCreate) SetSha256(v string) *TicketAttachmentCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TicketAttachmentCreate) SetExpiresAt(v time.Time) *TicketAttachmentCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableExpiresAt(v *time.Time) *TicketAttachmentCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketAttachmentCreate) SetCreatedAt(v time.Time) *TicketAttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableCreatedAt(v *time.Time) *TicketAttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (_c *TicketAttachmentCreate) SetUploaderID(id int64) *TicketAttachmentCreate {
	_c.mutation.SetUploaderID(id)
	return _c
}

// SetNillableUploaderID sets the "uploader" edge to the User entity by ID if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableUploaderID(id *int64) *TicketAttachmentCreate {
	if id != nil {
		_c = _c.SetUploaderID(*id)
	}
	return _c
}

// SetUploader sets the "uploader" edge to the User entity.
func (_c *TicketAttachmentCreate) SetUploader(v *User) *TicketAttachmentCreate {
	return _c.SetUploaderID(v.ID)
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_c *TicketAttachmentCreate) SetTicket(v *Ticket) *TicketAttachmentCreate {
	return _c.SetTicketID(v.ID)
}

// SetMessage sets the "message" edge to the TicketMessage entity.
func (_c *TicketAttachmentCreate) SetMessage(v *TicketMessage) *TicketAttachmentCreate {
	return _c.SetMessageID(v.ID)
}

// Mutation returns the TicketAttachmentMutation object of the builder.
func (_c *TicketAttachmentCreate) Mutation() *TicketAttachmentMutation {
	return _c.mutation
}

// Save creates the TicketAttachment in the database.
func (_c *TicketAttachmentCreate) Save(ctx context.Context) (*TicketAttachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketAttachmentCreate) SaveX(ctx context.Context) *TicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketAttachmentCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := ticketattachment.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticketattachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketAttachmentCreate) check() error {
	if _, ok := _c.mutation.UploadToken(); !ok {
		return &ValidationError{Name: "upload_token", err: errors.New(`ent: missing required field "TicketAttachment.upload_token"`)}
	}
	if v, ok := _c.mutation.UploadToken(); ok {
		if err := ticketattachment.UploadTokenValidator(v); err != nil {
			return &ValidationError{Name: "upload_token", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.upload_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UploaderRole(); !ok {
		return &ValidationError{Name: "uploader_role", err: errors.New(`ent: missing required field "TicketAttachment.uploader_role"`)}
	}
	if v, ok := _c.mutation.UploaderRole(); ok {
		if err := ticketattachment.UploaderRoleValidator(v); err != nil {
			return &ValidationError{Name: "uploader_role", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.uploader_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "TicketAttachment.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := ticketattachment.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageProvider(); !ok {
		return &ValidationError{Name: "storage_provider", err: errors.New(`ent: missing required field "TicketAttachment.storage_provider"`)}
	}
	if v, ok := _c.mutation.StorageProvider(); ok {
		if err := ticketattachment.StorageProviderValidator(v); err != nil {
			return &ValidationError{Name: "storage_provider", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.storage_provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "TicketAttachment.object_key"`)}
	}
	if v, ok := _c.mutation.ObjectKey(); ok {
		if err := ticketattachment.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.object_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "TicketAttachment.original_name"`)}
	}
	if v, ok := _c.mutation.OriginalName(); ok {
		if err := ticketattachment.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.original_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "TicketAttachment.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := ticketattachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ByteSize(); !ok {
		return &ValidationError{Name: "byte_size", err: errors.New(`ent: missing required field "TicketAttachment.byte_size"`)}
	}
	if v, ok := _c.mutation.ByteSize(); ok {
		if err := ticketattachment.ByteSizeValidator(v); err != nil {
			return &ValidationError{Name: "byte_size", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.byte_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "TicketAttachment.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := ticketattachment.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TicketAttachment.created_at"`)}
	}
	return nil
}

func (_c *TicketAttachmentCreate) sqlSave(ctx context.Context) (*TicketAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketAttachmentCreate) createSpec() (*TicketAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketattachment.Table, sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UploadToken(); ok {
		_spec.SetField(ticketattachment.FieldUploadToken, field.TypeString, value)
		_node.UploadToken = value
	}
	if value, ok := _c.mutation.UploaderRole(); ok {
		_spec.SetField(ticketattachment.FieldUploaderRole, field.TypeString, value)
		_node.UploaderRole = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(ticketattachment.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.StorageProvider(); ok {
		_spec.SetField(ticketattachment.FieldStorageProvider, field.TypeString, value)
		_node.StorageProvider = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(ticketattachment.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.OriginalName(); ok {
		_spec.SetField(ticketattachment.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(ticketattachment.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.ByteSize(); ok {
		_spec.SetField(ticketattachment.FieldByteSize, field.TypeInt64, value)
		_node.ByteSize = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(ticketattachment.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(ticketattachment.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticketattachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketattachment.UploaderTable,
			Columns: []string{ticketattachment.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UploadedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketattachment.TicketTable,
			Columns: []string{ticketattachment.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TicketID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketattachment.MessageTable,
			Columns: []string{ticketattachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MessageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketAttachment.Create().
//		SetUploadToken(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketAttachmentUpsert) {
//			SetUploadToken(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketAttachmentCreate) OnConflict(opts ...sql.ConflictOption) *TicketAttachmentUpsertOne {
	_c.conflict = opts
	return &TicketAttachmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketAttachmentCreate) OnConflictColumns(columns ...string) *TicketAttachmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketAttachmentUpsertOne{
		create: _c,
	}
}

type (
	// TicketAttachmentUpsertOne is the builder for "upsert"-ing
	//  one TicketAttachment node.
	TicketAttachmentUpsertOne struct {
		create *TicketAttachmentCreate
	}

	// TicketAttachmentUpsert is the "OnConflict" setter.
	TicketAttachmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUploadToken sets the "upload_token" field.
func (u *TicketAttachmentUpsert) SetUploadToken(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldUploadToken, v)
	return u
}

// UpdateUploadToken sets the "upload_token" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateUploadToken() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldUploadToken)
	return u
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *TicketAttachmentUpsert) SetUploadedBy(v int64) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldUploadedBy, v)
	return u
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateUploadedBy() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldUploadedBy)
	return u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *TicketAttachmentUpsert) ClearUploadedBy() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldUploadedBy)
	return u
}

// SetUploaderRole sets the "uploader_role" field.
func (u *TicketAttachmentUpsert) SetUploaderRole(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldUploaderRole, v)
	return u
}

// UpdateUploaderRole sets the "uploader_role" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateUploaderRole() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldUploaderRole)
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketAttachmentUpsert) SetTicketID(v int64) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldTicketID, v)
	return u
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateTicketID() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldTicketID)
	return u
}

// ClearTicketID clears the value of the "ticket_id" field.
func (u *TicketAttachmentUpsert) ClearTicketID() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldTicketID)
	return u
}

// SetMessageID sets the "message_id" field.
func (u *TicketAttachmentUpsert) SetMessageID(v int64) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateMessageID() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldMessageID)
	return u
}

// ClearMessageID clears the value of the "message_id" field.
func (u *TicketAttachmentUpsert) ClearMessageID() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldMessageID)
	return u
}

// SetState sets the "state" field.
func (u *TicketAttachmentUpsert) SetState(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateState() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldState)
	return u
}

// SetStorageProvider sets the "storage_provider" field.
func (u *TicketAttachmentUpsert) SetStorageProvider(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldStorageProvider, v)
	return u
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateStorageProvider() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldStorageProvider)
	return u
}

// SetObjectKey sets the "object_key" field.
func (u *TicketAttachmentUpsert) SetObjectKey(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldObjectKey, v)
	return u
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateObjectKey() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldObjectKey)
	return u
}

// SetOriginalName sets the "original_name" field.
func (u *TicketAttachmentUpsert) SetOriginalName(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldOriginalName, v)
	return u
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateOriginalName() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldOriginalName)
	return u
}

// SetContentType sets the "content_type" field.
func (u *TicketAttachmentUpsert) SetContentType(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateContentType() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldContentType)
	return u
}

// SetByteSize sets the "byte_size" field.
func (u *TicketAttachmentUpsert) SetByteSize(v int64) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldByteSize, v)
	return u
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateByteSize() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldByteSize)
	return u
}

// AddByteSize adds v to the "byte_size" field.
func (u *TicketAttachmentUpsert) AddByteSize(v int64) *TicketAttachmentUpsert {
	u.Add(ticketattachment.FieldByteSize, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *TicketAttachmentUpsert) SetSha256(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateSha256() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldSha256)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *TicketAttachmentUpsert) SetExpiresAt(v time.Time) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateExpiresAt() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TicketAttachmentUpsert) ClearExpiresAt() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketAttachmentUpsertOne) UpdateNewValues() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ticketattachment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketAttachmentUpsertOne) Ignore() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketAttachmentUpsertOne) DoNothing() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketAttachmentCreate.OnConflict
// documentation for more info.
func (u *TicketAttachmentUpsertOne) Update(set func(*TicketAttachmentUpsert)) *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUploadToken sets the "upload_token" field.
func (u *TicketAttachmentUpsertOne) SetUploadToken(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetUploadToken(v)
	})
}

// UpdateUploadToken sets the "upload_token" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateUploadToken() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateUploadToken()
	})
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *TicketAttachmentUpsertOne) SetUploadedBy(v int64) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetUploadedBy(v)
	})
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateUploadedBy() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateUploadedBy()
	})
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *TicketAttachmentUpsertOne) ClearUploadedBy() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearUploadedBy()
	})
}

// SetUploaderRole sets the "uploader_role" field.
func (u *TicketAttachmentUpsertOne) SetUploaderRole(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetUploaderRole(v)
	})
}

// UpdateUploaderRole sets the "uploader_role" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateUploaderRole() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateUploaderRole()
	})
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketAttachmentUpsertOne) SetTicketID(v int64) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateTicketID() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateTicketID()
	})
}

// ClearTicketID clears the value of the "ticket_id" field.
func (u *TicketAttachmentUpsertOne) ClearTicketID() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearTicketID()
	})
}

// SetMessageID sets the "message_id" field.
func (u *TicketAttachmentUpsertOne) SetMessageID(v int64) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateMessageID() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// ClearMessageID clears the value of the "message_id" field.
func (u *TicketAttachmentUpsertOne) ClearMessageID() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearMessageID()
	})
}

// SetState sets the "state" field.
func (u *TicketAttachmentUpsertOne) SetState(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateState() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateState()
	})
}

// SetStorageProvider sets the "storage_provider" field.
func (u *TicketAttachmentUpsertOne) SetStorageProvider(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetStorageProvider(v)
	})
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateStorageProvider() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateStorageProvider()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *TicketAttachmentUpsertOne) SetObjectKey(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateObjectKey() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateObjectKey()
	})
}

// SetOriginalName sets the "original_name" field.
func (u *TicketAttachmentUpsertOne) SetOriginalName(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetOriginalName(v)
	})
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateOriginalName() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateOriginalName()
	})
}

// SetContentType sets the "content_type" field.
func (u *TicketAttachmentUpsertOne) SetContentType(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateContentType() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *TicketAttachmentUpsertOne) SetByteSize(v int64) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *TicketAttachmentUpsertOne) AddByteSize(v int64) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateByteSize() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateByteSize()
	})
}

// SetSha256 sets the "sha256" field.
func (u *TicketAttachmentUpsertOne) SetSha256(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateSha256() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateSha256()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *TicketAttachmentUpsertOne) SetExpiresAt(v time.Time) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateExpiresAt() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TicketAttachmentUpsertOne) ClearExpiresAt() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *TicketAttachmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketAttachmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketAttachmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketAttachmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketAttachmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketAttachmentCreateBulk is the builder for creating many TicketAttachment entities in bulk.
type TicketAttachmentCreateBulk struct {
	config
	err      error
	builders []*TicketAttachmentCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketAttachment entities in the database.
func (_c *TicketAttachmentCreateBulk) Save(ctx context.Context) ([]*TicketAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketAttachmentCreateBulk) SaveX(ctx context.Context) []*TicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketAttachment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketAttachmentUpsert) {
//			SetUploadToken(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketAttachmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketAttachmentUpsertBulk {
	_c.conflict = opts
	return &TicketAttachmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketAttachmentCreateBulk) OnConflictColumns(columns ...string) *TicketAttachmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketAttachmentUpsertBulk{
		create: _c,
	}
}

// TicketAttachmentUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketAttachment nodes.
type TicketAttachmentUpsertBulk struct {
	create *TicketAttachmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketAttachmentUpsertBulk) UpdateNewValues() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ticketattachment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketAttachmentUpsertBulk) Ignore() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketAttachmentUpsertBulk) DoNothing() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketAttachmentCreateBulk.OnConflict
// documentation for more info.
func (u *TicketAttachmentUpsertBulk) Update(set func(*TicketAttachmentUpsert)) *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUploadToken sets the "upload_token" field.
func (u *TicketAttachmentUpsertBulk) SetUploadToken(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetUploadToken(v)
	})
}

// UpdateUploadToken sets the "upload_token" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateUploadToken() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateUploadToken()
	})
}

// SetUploadedBy sets the "uploaded_by" field.
func (u *TicketAttachmentUpsertBulk) SetUploadedBy(v int64) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetUploadedBy(v)
	})
}

// UpdateUploadedBy sets the "uploaded_by" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateUploadedBy() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateUploadedBy()
	})
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (u *TicketAttachmentUpsertBulk) ClearUploadedBy() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearUploadedBy()
	})
}

// SetUploaderRole sets the "uploader_role" field.
func (u *TicketAttachmentUpsertBulk) SetUploaderRole(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetUploaderRole(v)
	})
}

// UpdateUploaderRole sets the "uploader_role" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateUploaderRole() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateUploaderRole()
	})
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketAttachmentUpsertBulk) SetTicketID(v int64) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateTicketID() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateTicketID()
	})
}

// ClearTicketID clears the value of the "ticket_id" field.
func (u *TicketAttachmentUpsertBulk) ClearTicketID() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearTicketID()
	})
}

// SetMessageID sets the "message_id" field.
func (u *TicketAttachmentUpsertBulk) SetMessageID(v int64) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateMessageID() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateMessageID()
	})
}

// ClearMessageID clears the value of the "message_id" field.
func (u *TicketAttachmentUpsertBulk) ClearMessageID() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearMessageID()
	})
}

// SetState sets the "state" field.
func (u *TicketAttachmentUpsertBulk) SetState(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateState() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateState()
	})
}

// SetStorageProvider sets the "storage_provider" field.
func (u *TicketAttachmentUpsertBulk) SetStorageProvider(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetStorageProvider(v)
	})
}

// UpdateStorageProvider sets the "storage_provider" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateStorageProvider() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateStorageProvider()
	})
}

// SetObjectKey sets the "object_key" field.
func (u *TicketAttachmentUpsertBulk) SetObjectKey(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetObjectKey(v)
	})
}

// UpdateObjectKey sets the "object_key" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateObjectKey() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateObjectKey()
	})
}

// SetOriginalName sets the "original_name" field.
func (u *TicketAttachmentUpsertBulk) SetOriginalName(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetOriginalName(v)
	})
}

// UpdateOriginalName sets the "original_name" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateOriginalName() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateOriginalName()
	})
}

// SetContentType sets the "content_type" field.
func (u *TicketAttachmentUpsertBulk) SetContentType(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateContentType() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *TicketAttachmentUpsertBulk) SetByteSize(v int64) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *TicketAttachmentUpsertBulk) AddByteSize(v int64) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateByteSize() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateByteSize()
	})
}

// SetSha256 sets the "sha256" field.
func (u *TicketAttachmentUpsertBulk) SetSha256(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateSha256() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateSha256()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *TicketAttachmentUpsertBulk) SetExpiresAt(v time.Time) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateExpiresAt() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *TicketAttachmentUpsertBulk) ClearExpiresAt() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *TicketAttachmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketAttachmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketAttachmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketAttachmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
