// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketAttachment is the model entity for the TicketAttachment schema.
type TicketAttachment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UploadToken holds the value of the "upload_token" field.
	UploadToken string `json:"upload_token,omitempty"`
	// UploadedBy holds the value of the "uploaded_by" field.
	UploadedBy *int64 `json:"uploaded_by,omitempty"`
	// UploaderRole holds the value of the "uploader_role" field.
	UploaderRole string `json:"uploader_role,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID *int64 `json:"ticket_id,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID *int64 `json:"message_id,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// StorageProvider holds the value of the "storage_provider" field.
	StorageProvider string `json:"storage_provider,omitempty"`
	// ObjectKey holds the value of the "object_key" field.
	ObjectKey string `json:"object_key,omitempty"`
	// OriginalName holds the value of the "original_name" field.
	OriginalName string `json:"original_name,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// ByteSize holds the value of the "byte_size" field.
	ByteSize int64 `json:"byte_size,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketAttachmentQuery when eager-loading is set.
	Edges        TicketAttachmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketAttachmentEdges holds the relations/edges for other nodes in the graph.
type TicketAttachmentEdges struct {
	// Uploader holds the value of the uploader edge.
	Uploader *User `json:"uploader,omitempty"`
	// Ticket holds the value of the ticket edge.
	Ticket *Ticket `json:"ticket,omitempty"`
	// Message holds the value of the message edge.
	Message *TicketMessage `json:"message,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UploaderOrErr returns the Uploader value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketAttachmentEdges) UploaderOrErr() (*User, error) {
	if e.Uploader != nil {
		return e.Uploader, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "uploader"}
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketAttachmentEdges) TicketOrErr() (*Ticket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: ticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketAttachmentEdges) MessageOrErr() (*TicketMessage, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: ticketmessage.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketAttachment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketattachment.FieldID, ticketattachment.FieldUploadedBy, ticketattachment.FieldTicketID, ticketattachment.FieldMessageID, ticketattachment.FieldByteSize:
			values[i] = new(sql.NullInt64)
		case ticketattachment.FieldUploadToken, ticketattachment.FieldUploaderRole, ticketattachment.FieldState, ticketattachment.FieldStorageProvider, ticketattachment.FieldObjectKey, ticketattachment.FieldOriginalName, ticketattachment.FieldContentType, ticketattachment.FieldSha256:
			values[i] = new(sql.NullString)
		case ticketattachment.FieldExpiresAt, ticketattachment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketAttachment fields.
func (_m *TicketAttachment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketattachment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ticketattachment.FieldUploadToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upload_token", values[i])
			} else if value.Valid {
				_m.UploadToken = value.String
			}
		case ticketattachment.FieldUploadedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_by", values[i])
			} else if value.Valid {
				_m.UploadedBy = new(int64)
				*_m.UploadedBy = value.Int64
			}
		case ticketattachment.FieldUploaderRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uploader_role", values[i])
			} else if value.Valid {
				_m.UploaderRole = value.String
			}
		case ticketattachment.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = new(int64)
				*_m.TicketID = value.Int64
			}
		case ticketattachment.FieldMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = new(int64)
				*_m.MessageID = value.Int64
			}
		case ticketattachment.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case ticketattachment.FieldStorageProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_provider", values[i])
			} else if value.Valid {
				_m.StorageProvider = value.String
			}
		case ticketattachment.FieldObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_key", values[i])
			} else if value.Valid {
				_m.ObjectKey = value.String
			}
		case ticketattachment.FieldOriginalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_name", values[i])
			} else if value.Valid {
				_m.OriginalName = value.String
			}
		case ticketattachment.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case ticketattachment.FieldByteSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field byte_size", values[i])
			} else if value.Valid {
				_m.ByteSize = value.Int64
			}
		case ticketattachment.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case ticketattachment.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case ticketattachment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketAttachment.
// This includes values selected through modifiers, order, etc.
func (_m *TicketAttachment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUploader queries the "uploader" edge of the TicketAttachment entity.
func (_m *TicketAttachment) QueryUploader() *UserQuery {
	return NewTicketAttachmentClient(_m.config).QueryUploader(_m)
}

// QueryTicket queries the "ticket" edge of the TicketAttachment entity.
func (_m *TicketAttachment) QueryTicket() *TicketQuery {
	return NewTicketAttachmentClient(_m.config).QueryTicket(_m)
}

// QueryMessage queries the "message" edge of the TicketAttachment entity.
func (_m *TicketAttachment) QueryMessage() *TicketMessageQuery {
	return NewTicketAttachmentClient(_m.config).QueryMessage(_m)
}

// Update returns a builder for updating this TicketAttachment.
// Note that you need to call TicketAttachment.Unwrap() before calling this method if this TicketAttachment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketAttachment) Update() *TicketAttachmentUpdateOne {
	return NewTicketAttachmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketAttachment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketAttachment) Unwrap() *TicketAttachment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TicketAttachment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketAttachment) String() string {
	var builder strings.Builder
	builder.WriteString("TicketAttachment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("upload_token=")
	builder.WriteString(_m.UploadToken)
	builder.WriteString(", ")
	if v := _m.UploadedBy; v != nil {
		builder.WriteString("uploaded_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("uploader_role=")
	builder.WriteString(_m.UploaderRole)
	builder.WriteString(", ")
	if v := _m.TicketID; v != nil {
		builder.WriteString("ticket_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MessageID; v != nil {
		builder.WriteString("message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("storage_provider=")
	builder.WriteString(_m.StorageProvider)
	builder.WriteString(", ")
	builder.WriteString("object_key=")
	builder.WriteString(_m.ObjectKey)
	builder.WriteString(", ")
	builder.WriteString("original_name=")
	builder.WriteString(_m.OriginalName)
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("byte_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.ByteSize))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TicketAttachments is a parsable slice of TicketAttachment.
type TicketAttachments []*TicketAttachment
