// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketMessageUpdate is the builder for updating TicketMessage entities.
type TicketMessageUpdate struct {
	config
	hooks    []Hook
	mutation *TicketMessageMutation
}

// Where appends a list predicates to the TicketMessageUpdate builder.
func (_u *TicketMessageUpdate) Where(ps ...predicate.TicketMessage) *TicketMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *TicketMessageUpdate) SetTicketID(v int64) *TicketMessageUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableTicketID(v *int64) *TicketMessageUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *TicketMessageUpdate) SetAuthorID(v int64) *TicketMessageUpdate {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableAuthorID(v *int64) *TicketMessageUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// ClearAuthorID clears the value of the "author_id" field.
func (_u *TicketMessageUpdate) ClearAuthorID() *TicketMessageUpdate {
	_u.mutation.ClearAuthorID()
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *TicketMessageUpdate) SetAuthorRole(v string) *TicketMessageUpdate {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableAuthorRole(v *string) *TicketMessageUpdate {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *TicketMessageUpdate) SetVisibility(v string) *TicketMessageUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableVisibility(v *string) *TicketMessageUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *TicketMessageUpdate) SetAuthorName(v string) *TicketMessageUpdate {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableAuthorName(v *string) *TicketMessageUpdate {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *TicketMessageUpdate) SetBody(v string) *TicketMessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableBody(v *string) *TicketMessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *TicketMessageUpdate) SetTicket(v *Ticket) *TicketMessageUpdate {
	return _u.SetTicketID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *TicketMessageUpdate) SetAuthor(v *User) *TicketMessageUpdate {
	return _u.SetAuthorID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the TicketAttachment entity by IDs.
func (_u *TicketMessageUpdate) AddAttachmentIDs(ids ...int64) *TicketMessageUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the TicketAttachment entity.
func (_u *TicketMessageUpdate) AddAttachments(v ...*TicketAttachment) *TicketMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the TicketMessageMutation object of the builder.
func (_u *TicketMessageUpdate) Mutation() *TicketMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *TicketMessageUpdate) ClearTicket() *TicketMessageUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *TicketMessageUpdate) ClearAuthor() *TicketMessageUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearAttachments clears all "attachments" edges to the TicketAttachment entity.
func (_u *TicketMessageUpdate) ClearAttachments() *TicketMessageUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to TicketAttachment entities by IDs.
func (_u *TicketMessageUpdate) RemoveAttachmentIDs(ids ...int64) *TicketMessageUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to TicketAttachment entities.
func (_u *TicketMessageUpdate) RemoveAttachments(v ...*TicketAttachment) *TicketMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketMessageUpdate) check() error {
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := ticketmessage.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := ticketmessage.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorName(); ok {
		if err := ticketmessage.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.author_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := ticketmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.body": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketMessage.ticket"`)
	}
	return nil
}

func (_u *TicketMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketmessage.Table, ticketmessage.Columns, sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(ticketmessage.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(ticketmessage.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(ticketmessage.FieldAuthorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(ticketmessage.FieldBody, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.AuthorTable,
			Columns: []string{ticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.AuthorTable,
			Columns: []string{ticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketMessageUpdateOne is the builder for updating a single TicketMessage entity.
type TicketMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketMessageMutation
}

// SetTicketID sets the "ticket_id" field.
func (_u *TicketMessageUpdateOne) SetTicketID(v int64) *TicketMessageUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableTicketID(v *int64) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *TicketMessageUpdateOne) SetAuthorID(v int64) *TicketMessageUpdateOne {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableAuthorID(v *int64) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// ClearAuthorID clears the value of the "author_id" field.
func (_u *TicketMessageUpdateOne) ClearAuthorID() *TicketMessageUpdateOne {
	_u.mutation.ClearAuthorID()
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *TicketMessageUpdateOne) SetAuthorRole(v string) *TicketMessageUpdateOne {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableAuthorRole(v *string) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *TicketMessageUpdateOne) SetVisibility(v string) *TicketMessageUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableVisibility(v *string) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *TicketMessageUpdateOne) SetAuthorName(v string) *TicketMessageUpdateOne {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableAuthorName(v *string) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *TicketMessageUpdateOne) SetBody(v string) *TicketMessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableBody(v *string) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *TicketMessageUpdateOne) SetTicket(v *Ticket) *TicketMessageUpdateOne {
	return _u.SetTicketID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *TicketMessageUpdateOne) SetAuthor(v *User) *TicketMessageUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the TicketAttachment entity by IDs.
func (_u *TicketMessageUpdateOne) AddAttachmentIDs(ids ...int64) *TicketMessageUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the TicketAttachment entity.
func (_u *TicketMessageUpdateOne) AddAttachments(v ...*TicketAttachment) *TicketMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the TicketMessageMutation object of the builder.
func (_u *TicketMessageUpdateOne) Mutation() *TicketMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *TicketMessageUpdateOne) ClearTicket() *TicketMessageUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *TicketMessageUpdateOne) ClearAuthor() *TicketMessageUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearAttachments clears all "attachments" edges to the TicketAttachment entity.
func (_u *TicketMessageUpdateOne) ClearAttachments() *TicketMessageUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to TicketAttachment entities by IDs.
func (_u *TicketMessageUpdateOne) RemoveAttachmentIDs(ids ...int64) *TicketMessageUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to TicketAttachment entities.
func (_u *TicketMessageUpdateOne) RemoveAttachments(v ...*TicketAttachment) *TicketMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the TicketMessageUpdate builder.
func (_u *TicketMessageUpdateOne) Where(ps ...predicate.TicketMessage) *TicketMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketMessageUpdateOne) Select(field string, fields ...string) *TicketMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TicketMessage entity.
func (_u *TicketMessageUpdateOne) Save(ctx context.Context) (*TicketMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketMessageUpdateOne) SaveX(ctx context.Context) *TicketMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketMessageUpdateOne) check() error {
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := ticketmessage.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := ticketmessage.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorName(); ok {
		if err := ticketmessage.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.author_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := ticketmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.body": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketMessage.ticket"`)
	}
	return nil
}

func (_u *TicketMessageUpdateOne) sqlSave(ctx context.Context) (_node *TicketMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketmessage.Table, ticketmessage.Columns, sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TicketMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticketmessage.FieldID)
		for _, f := range fields {
			if !ticketmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticketmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(ticketmessage.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(ticketmessage.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(ticketmessage.FieldAuthorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(ticketmessage.FieldBody, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.AuthorTable,
			Columns: []string{ticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.AuthorTable,
			Columns: []string{ticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TicketMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
