// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketEventUpdate is the builder for updating TicketEvent entities.
type TicketEventUpdate struct {
	config
	hooks    []Hook
	mutation *TicketEventMutation
}

// Where appends a list predicates to the TicketEventUpdate builder.
func (_u *TicketEventUpdate) Where(ps ...predicate.TicketEvent) *TicketEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *TicketEventUpdate) SetTicketID(v int64) *TicketEventUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *TicketEventUpdate) SetNillableTicketID(v *int64) *TicketEventUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *TicketEventUpdate) SetActorID(v int64) *TicketEventUpdate {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *TicketEventUpdate) SetNillableActorID(v *int64) *TicketEventUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *TicketEventUpdate) ClearActorID() *TicketEventUpdate {
	_u.mutation.ClearActorID()
	return _u
}

// SetActorRole sets the "actor_role" field.
func (_u *TicketEventUpdate) SetActorRole(v string) *TicketEventUpdate {
	_u.mutation.SetActorRole(v)
	return _u
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_u *TicketEventUpdate) SetNillableActorRole(v *string) *TicketEventUpdate {
	if v != nil {
		_u.SetActorRole(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *TicketEventUpdate) SetEventType(v string) *TicketEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *TicketEventUpdate) SetNillableEventType(v *string) *TicketEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetFromStatus sets the "from_status" field.
func (_u *TicketEventUpdate) SetFromStatus(v string) *TicketEventUpdate {
	_u.mutation.SetFromStatus(v)
	return _u
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_u *TicketEventUpdate) SetNillableFromStatus(v *string) *TicketEventUpdate {
	if v != nil {
		_u.SetFromStatus(*v)
	}
	return _u
}

// ClearFromStatus clears the value of the "from_status" field.
func (_u *TicketEventUpdate) ClearFromStatus() *TicketEventUpdate {
	_u.mutation.ClearFromStatus()
	return _u
}

// SetToStatus sets the "to_status" field.
func (_u *TicketEventUpdate) SetToStatus(v string) *TicketEventUpdate {
	_u.mutation.SetToStatus(v)
	return _u
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_u *TicketEventUpdate) SetNillableToStatus(v *string) *TicketEventUpdate {
	if v != nil {
		_u.SetToStatus(*v)
	}
	return _u
}

// ClearToStatus clears the value of the "to_status" field.
func (_u *TicketEventUpdate) ClearToStatus() *TicketEventUpdate {
	_u.mutation.ClearToStatus()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *TicketEventUpdate) SetPayload(v map[string]interface{}) *TicketEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *TicketEventUpdate) SetVisibility(v string) *TicketEventUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *TicketEventUpdate) SetNillableVisibility(v *string) *TicketEventUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *TicketEventUpdate) SetTicket(v *Ticket) *TicketEventUpdate {
	return _u.SetTicketID(v.ID)
}

// SetActor sets the "actor" edge to the User entity.
func (_u *TicketEventUpdate) SetActor(v *User) *TicketEventUpdate {
	return _u.SetActorID(v.ID)
}

// Mutation returns the TicketEventMutation object of the builder.
func (_u *TicketEventUpdate) Mutation() *TicketEventMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *TicketEventUpdate) ClearTicket() *TicketEventUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// ClearActor clears the "actor" edge to the User entity.
func (_u *TicketEventUpdate) ClearActor() *TicketEventUpdate {
	_u.mutation.ClearActor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketEventUpdate) check() error {
	if v, ok := _u.mutation.ActorRole(); ok {
		if err := ticketevent.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.actor_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := ticketevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromStatus(); ok {
		if err := ticketevent.FromStatusValidator(v); err != nil {
			return &ValidationError{Name: "from_status", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.from_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToStatus(); ok {
		if err := ticketevent.ToStatusValidator(v); err != nil {
			return &ValidationError{Name: "to_status", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.to_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := ticketevent.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.visibility": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketEvent.ticket"`)
	}
	return nil
}

func (_u *TicketEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketevent.Table, ticketevent.Columns, sqlgraph.NewFieldSpec(ticketevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActorRole(); ok {
		_spec.SetField(ticketevent.FieldActorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(ticketevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromStatus(); ok {
		_spec.SetField(ticketevent.FieldFromStatus, field.TypeString, value)
	}
	if _u.mutation.FromStatusCleared() {
		_spec.ClearField(ticketevent.FieldFromStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ToStatus(); ok {
		_spec.SetField(ticketevent.FieldToStatus, field.TypeString, value)
	}
	if _u.mutation.ToStatusCleared() {
		_spec.ClearField(ticketevent.FieldToStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(ticketevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(ticketevent.FieldVisibility, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.TicketTable,
			Columns: []string{ticketevent.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.TicketTable,
			Columns: []string{ticketevent.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.ActorTable,
			Columns: []string{ticketevent.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.ActorTable,
			Columns: []string{ticketevent.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketEventUpdateOne is the builder for updating a single TicketEvent entity.
type TicketEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketEventMutation
}

// SetTicketID sets the "ticket_id" field.
func (_u *TicketEventUpdateOne) SetTicketID(v int64) *TicketEventUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *TicketEventUpdateOne) SetNillableTicketID(v *int64) *TicketEventUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *TicketEventUpdateOne) SetActorID(v int64) *TicketEventUpdateOne {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *TicketEventUpdateOne) SetNillableActorID(v *int64) *TicketEventUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *TicketEventUpdateOne) ClearActorID() *TicketEventUpdateOne {
	_u.mutation.ClearActorID()
	return _u
}

// SetActorRole sets the "actor_role" field.
func (_u *TicketEventUpdateOne) SetActorRole(v string) *TicketEventUpdateOne {
	_u.mutation.SetActorRole(v)
	return _u
}

// SetNillableActorRole sets the "actor_role" field if the given value is not nil.
func (_u *TicketEventUpdateOne) SetNillableActorRole(v *string) *TicketEventUpdateOne {
	if v != nil {
		_u.SetActorRole(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *TicketEventUpdateOne) SetEventType(v string) *TicketEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *TicketEventUpdateOne) SetNillableEventType(v *string) *TicketEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetFromStatus sets the "from_status" field.
func (_u *TicketEventUpdateOne) SetFromStatus(v string) *TicketEventUpdateOne {
	_u.mutation.SetFromStatus(v)
	return _u
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_u *TicketEventUpdateOne) SetNillableFromStatus(v *string) *TicketEventUpdateOne {
	if v != nil {
		_u.SetFromStatus(*v)
	}
	return _u
}

// ClearFromStatus clears the value of the "from_status" field.
func (_u *TicketEventUpdateOne) ClearFromStatus() *TicketEventUpdateOne {
	_u.mutation.ClearFromStatus()
	return _u
}

// SetToStatus sets the "to_status" field.
func (_u *TicketEventUpdateOne) SetToStatus(v string) *TicketEventUpdateOne {
	_u.mutation.SetToStatus(v)
	return _u
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_u *TicketEventUpdateOne) SetNillableToStatus(v *string) *TicketEventUpdateOne {
	if v != nil {
		_u.SetToStatus(*v)
	}
	return _u
}

// ClearToStatus clears the value of the "to_status" field.
func (_u *TicketEventUpdateOne) ClearToStatus() *TicketEventUpdateOne {
	_u.mutation.ClearToStatus()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *TicketEventUpdateOne) SetPayload(v map[string]interface{}) *TicketEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *TicketEventUpdateOne) SetVisibility(v string) *TicketEventUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *TicketEventUpdateOne) SetNillableVisibility(v *string) *TicketEventUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_u *TicketEventUpdateOne) SetTicket(v *Ticket) *TicketEventUpdateOne {
	return _u.SetTicketID(v.ID)
}

// SetActor sets the "actor" edge to the User entity.
func (_u *TicketEventUpdateOne) SetActor(v *User) *TicketEventUpdateOne {
	return _u.SetActorID(v.ID)
}

// Mutation returns the TicketEventMutation object of the builder.
func (_u *TicketEventUpdateOne) Mutation() *TicketEventMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (_u *TicketEventUpdateOne) ClearTicket() *TicketEventUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// ClearActor clears the "actor" edge to the User entity.
func (_u *TicketEventUpdateOne) ClearActor() *TicketEventUpdateOne {
	_u.mutation.ClearActor()
	return _u
}

// Where appends a list predicates to the TicketEventUpdate builder.
func (_u *TicketEventUpdateOne) Where(ps ...predicate.TicketEvent) *TicketEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketEventUpdateOne) Select(field string, fields ...string) *TicketEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TicketEvent entity.
func (_u *TicketEventUpdateOne) Save(ctx context.Context) (*TicketEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketEventUpdateOne) SaveX(ctx context.Context) *TicketEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketEventUpdateOne) check() error {
	if v, ok := _u.mutation.ActorRole(); ok {
		if err := ticketevent.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.actor_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := ticketevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromStatus(); ok {
		if err := ticketevent.FromStatusValidator(v); err != nil {
			return &ValidationError{Name: "from_status", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.from_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToStatus(); ok {
		if err := ticketevent.ToStatusValidator(v); err != nil {
			return &ValidationError{Name: "to_status", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.to_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := ticketevent.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.visibility": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketEvent.ticket"`)
	}
	return nil
}

func (_u *TicketEventUpdateOne) sqlSave(ctx context.Context) (_node *TicketEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketevent.Table, ticketevent.Columns, sqlgraph.NewFieldSpec(ticketevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TicketEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticketevent.FieldID)
		for _, f := range fields {
			if !ticketevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticketevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActorRole(); ok {
		_spec.SetField(ticketevent.FieldActorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(ticketevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromStatus(); ok {
		_spec.SetField(ticketevent.FieldFromStatus, field.TypeString, value)
	}
	if _u.mutation.FromStatusCleared() {
		_spec.ClearField(ticketevent.FieldFromStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ToStatus(); ok {
		_spec.SetField(ticketevent.FieldToStatus, field.TypeString, value)
	}
	if _u.mutation.ToStatusCleared() {
		_spec.ClearField(ticketevent.FieldToStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(ticketevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(ticketevent.FieldVisibility, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.TicketTable,
			Columns: []string{ticketevent.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.TicketTable,
			Columns: []string{ticketevent.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.ActorTable,
			Columns: []string{ticketevent.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.ActorTable,
			Columns: []string{ticketevent.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TicketEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
