// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketEventCreate is the builder for creating a TicketEvent entity.
type TicketEventCreate struct {
	config
	mutation *TicketEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTicketID sets the "ticket_id" field.
func (_c *TicketEventCreate) SetTicketID(v int64) *TicketEventCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *TicketEventCreate) SetActorID(v int64) *TicketEventCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_c *TicketEventCreate) SetNillableActorID(v *int64) *TicketEventCreate {
	if v != nil {
		_c.SetActorID(*v)
	}
	return _c
}

// SetActorRole sets the "actor_role" field.
func (_c *TicketEventCreate) SetActorRole(v string) *TicketEventCreate {
	_c.mutation.SetActorRole(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *TicketEventCreate) SetEventType(v string) *TicketEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetFromStatus sets the "from_status" field.
func (_c *TicketEventCreate) SetFromStatus(v string) *TicketEventCreate {
	_c.mutation.SetFromStatus(v)
	return _c
}

// SetNillableFromStatus sets the "from_status" field if the given value is not nil.
func (_c *TicketEventCreate) SetNillableFromStatus(v *string) *TicketEventCreate {
	if v != nil {
		_c.SetFromStatus(*v)
	}
	return _c
}

// SetToStatus sets the "to_status" field.
func (_c *TicketEventCreate) SetToStatus(v string) *TicketEventCreate {
	_c.mutation.SetToStatus(v)
	return _c
}

// SetNillableToStatus sets the "to_status" field if the given value is not nil.
func (_c *TicketEventCreate) SetNillableToStatus(v *string) *TicketEventCreate {
	if v != nil {
		_c.SetToStatus(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *TicketEventCreate) SetPayload(v map[string]interface{}) *TicketEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *TicketEventCreate) SetVisibility(v string) *TicketEventCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketEventCreate) SetCreatedAt(v time.Time) *TicketEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketEventCreate) SetNillableCreatedAt(v *time.Time) *TicketEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_c *TicketEventCreate) SetTicket(v *Ticket) *TicketEventCreate {
	return _c.SetTicketID(v.ID)
}

// SetActor sets the "actor" edge to the User entity.
func (_c *TicketEventCreate) SetActor(v *User) *TicketEventCreate {
	return _c.SetActorID(v.ID)
}

// Mutation returns the TicketEventMutation object of the builder.
func (_c *TicketEventCreate) Mutation() *TicketEventMutation {
	return _c.mutation
}

// Save creates the TicketEvent in the database.
func (_c *TicketEventCreate) Save(ctx context.Context) (*TicketEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketEventCreate) SaveX(ctx context.Context) *TicketEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketEventCreate) defaults() {
	if _, ok := _c.mutation.Payload(); !ok {
		v := ticketevent.DefaultPayload()
		_c.mutation.SetPayload(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticketevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketEventCreate) check() error {
	if _, ok := _c.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "TicketEvent.ticket_id"`)}
	}
	if _, ok := _c.mutation.ActorRole(); !ok {
		return &ValidationError{Name: "actor_role", err: errors.New(`ent: missing required field "TicketEvent.actor_role"`)}
	}
	if v, ok := _c.mutation.ActorRole(); ok {
		if err := ticketevent.ActorRoleValidator(v); err != nil {
			return &ValidationError{Name: "actor_role", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.actor_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "TicketEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := ticketevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FromStatus(); ok {
		if err := ticketevent.FromStatusValidator(v); err != nil {
			return &ValidationError{Name: "from_status", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.from_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ToStatus(); ok {
		if err := ticketevent.ToStatusValidator(v); err != nil {
			return &ValidationError{Name: "to_status", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.to_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "TicketEvent.payload"`)}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "TicketEvent.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := ticketevent.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "TicketEvent.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TicketEvent.created_at"`)}
	}
	if len(_c.mutation.TicketIDs()) == 0 {
		return &ValidationError{Name: "ticket", err: errors.New(`ent: missing required edge "TicketEvent.ticket"`)}
	}
	return nil
}

func (_c *TicketEventCreate) sqlSave(ctx context.Context) (*TicketEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketEventCreate) createSpec() (*TicketEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketevent.Table, sqlgraph.NewFieldSpec(ticketevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ActorRole(); ok {
		_spec.SetField(ticketevent.FieldActorRole, field.TypeString, value)
		_node.ActorRole = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(ticketevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.FromStatus(); ok {
		_spec.SetField(ticketevent.FieldFromStatus, field.TypeString, value)
		_node.FromStatus = &value
	}
	if value, ok := _c.mutation.ToStatus(); ok {
		_spec.SetField(ticketevent.FieldToStatus, field.TypeString, value)
		_node.ToStatus = &value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(ticketevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(ticketevent.FieldVisibility, field.TypeString, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticketevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.TicketTable,
			Columns: []string{ticketevent.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TicketID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketevent.ActorTable,
			Columns: []string{ticketevent.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActorID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketEvent.Create().
//		SetTicketID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketEventUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketEventCreate) OnConflict(opts ...sql.ConflictOption) *TicketEventUpsertOne {
	_c.conflict = opts
	return &TicketEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketEventCreate) OnConflictColumns(columns ...string) *TicketEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketEventUpsertOne{
		create: _c,
	}
}

type (
	// TicketEventUpsertOne is the builder for "upsert"-ing
	//  one TicketEvent node.
	TicketEventUpsertOne struct {
		create *TicketEventCreate
	}

	// TicketEventUpsert is the "OnConflict" setter.
	TicketEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetTicketID sets the "ticket_id" field.
func (u *TicketEventUpsert) SetTicketID(v int64) *TicketEventUpsert {
	u.Set(ticketevent.FieldTicketID, v)
	return u
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketEventUpsert) UpdateTicketID() *TicketEventUpsert {
	u.SetExcluded(ticketevent.FieldTicketID)
	return u
}

// SetActorID sets the "actor_id" field.
func (u *TicketEventUpsert) SetActorID(v int64) *TicketEventUpsert {
	u.Set(ticketevent.FieldActorID, v)
	return u
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *TicketEventUpsert) UpdateActorID() *TicketEventUpsert {
	u.SetExcluded(ticketevent.FieldActorID)
	return u
}

// ClearActorID clears the value of the "actor_id" field.
func (u *TicketEventUpsert) ClearActorID() *TicketEventUpsert {
	u.SetNull(ticketevent.FieldActorID)
	return u
}

// SetActorRole sets the "actor_role" field.
func (u *TicketEventUpsert) SetActorRole(v string) *TicketEventUpsert {
	u.Set(ticketevent.FieldActorRole, v)
	return u
}

// UpdateActorRole sets the "actor_role" field to the value that was provided on create.
func (u *TicketEventUpsert) UpdateActorRole() *TicketEventUpsert {
	u.SetExcluded(ticketevent.FieldActorRole)
	return u
}

// SetEventType sets the "event_type" field.
func (u *TicketEventUpsert) SetEventType(v string) *TicketEventUpsert {
	u.Set(ticketevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *TicketEventUpsert) UpdateEventType() *TicketEventUpsert {
	u.SetExcluded(ticketevent.FieldEventType)
	return u
}

// SetFromStatus sets the "from_status" field.
func (u *TicketEventUpsert) SetFromStatus(v string) *TicketEventUpsert {
	u.Set(ticketevent.FieldFromStatus, v)
	return u
}

// UpdateFromStatus sets the "from_status" field to the value that was provided on create.
func (u *TicketEventUpsert) UpdateFromStatus() *TicketEventUpsert {
	u.SetExcluded(ticketevent.FieldFromStatus)
	return u
}

// ClearFromStatus clears the value of the "from_status" field.
func (u *TicketEventUpsert) ClearFromStatus() *TicketEventUpsert {
	u.SetNull(ticketevent.FieldFromStatus)
	return u
}

// SetToStatus sets the "to_status" field.
func (u *TicketEventUpsert) SetToStatus(v string) *TicketEventUpsert {
	u.Set(ticketevent.FieldToStatus, v)
	return u
}

// UpdateToStatus sets the "to_status" field to the value that was provided on create.
func (u *TicketEventUpsert) UpdateToStatus() *TicketEventUpsert {
	u.SetExcluded(ticketevent.FieldToStatus)
	return u
}

// ClearToStatus clears the value of the "to_status" field.
func (u *TicketEventUpsert) ClearToStatus() *TicketEventUpsert {
	u.SetNull(ticketevent.FieldToStatus)
	return u
}

// SetPayload sets the "payload" field.
func (u *TicketEventUpsert) SetPayload(v map[string]interface{}) *TicketEventUpsert {
	u.Set(ticketevent.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TicketEventUpsert) UpdatePayload() *TicketEventUpsert {
	u.SetExcluded(ticketevent.FieldPayload)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *TicketEventUpsert) SetVisibility(v string) *TicketEventUpsert {
	u.Set(ticketevent.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketEventUpsert) UpdateVisibility() *TicketEventUpsert {
	u.SetExcluded(ticketevent.FieldVisibility)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TicketEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketEventUpsertOne) UpdateNewValues() *TicketEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ticketevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketEventUpsertOne) Ignore() *TicketEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketEventUpsertOne) DoNothing() *TicketEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketEventCreate.OnConflict
// documentation for more info.
func (u *TicketEventUpsertOne) Update(set func(*TicketEventUpsert)) *TicketEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketEventUpsertOne) SetTicketID(v int64) *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketEventUpsertOne) UpdateTicketID() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateTicketID()
	})
}

// SetActorID sets the "actor_id" field.
func (u *TicketEventUpsertOne) SetActorID(v int64) *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *TicketEventUpsertOne) UpdateActorID() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateActorID()
	})
}

// ClearActorID clears the value of the "actor_id" field.
func (u *TicketEventUpsertOne) ClearActorID() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.ClearActorID()
	})
}

// SetActorRole sets the "actor_role" field.
func (u *TicketEventUpsertOne) SetActorRole(v string) *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetActorRole(v)
	})
}

// UpdateActorRole sets the "actor_role" field to the value that was provided on create.
func (u *TicketEventUpsertOne) UpdateActorRole() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateActorRole()
	})
}

// SetEventType sets the "event_type" field.
func (u *TicketEventUpsertOne) SetEventType(v string) *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *TicketEventUpsertOne) UpdateEventType() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateEventType()
	})
}

// SetFromStatus sets the "from_status" field.
func (u *TicketEventUpsertOne) SetFromStatus(v string) *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetFromStatus(v)
	})
}

// UpdateFromStatus sets the "from_status" field to the value that was provided on create.
func (u *TicketEventUpsertOne) UpdateFromStatus() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateFromStatus()
	})
}

// ClearFromStatus clears the value of the "from_status" field.
func (u *TicketEventUpsertOne) ClearFromStatus() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.ClearFromStatus()
	})
}

// SetToStatus sets the "to_status" field.
func (u *TicketEventUpsertOne) SetToStatus(v string) *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetToStatus(v)
	})
}

// UpdateToStatus sets the "to_status" field to the value that was provided on create.
func (u *TicketEventUpsertOne) UpdateToStatus() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateToStatus()
	})
}

// ClearToStatus clears the value of the "to_status" field.
func (u *TicketEventUpsertOne) ClearToStatus() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.ClearToStatus()
	})
}

// SetPayload sets the "payload" field.
func (u *TicketEventUpsertOne) SetPayload(v map[string]interface{}) *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TicketEventUpsertOne) UpdatePayload() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdatePayload()
	})
}

// SetVisibility sets the "visibility" field.
func (u *TicketEventUpsertOne) SetVisibility(v string) *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketEventUpsertOne) UpdateVisibility() *TicketEventUpsertOne {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateVisibility()
	})
}

// Exec executes the query.
func (u *TicketEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketEventCreateBulk is the builder for creating many TicketEvent entities in bulk.
type TicketEventCreateBulk struct {
	config
	err      error
	builders []*TicketEventCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketEvent entities in the database.
func (_c *TicketEventCreateBulk) Save(ctx context.Context) ([]*TicketEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketEventCreateBulk) SaveX(ctx context.Context) []*TicketEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketEventUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketEventUpsertBulk {
	_c.conflict = opts
	return &TicketEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketEventCreateBulk) OnConflictColumns(columns ...string) *TicketEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketEventUpsertBulk{
		create: _c,
	}
}

// TicketEventUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketEvent nodes.
type TicketEventUpsertBulk struct {
	create *TicketEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketEventUpsertBulk) UpdateNewValues() *TicketEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ticketevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketEventUpsertBulk) Ignore() *TicketEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketEventUpsertBulk) DoNothing() *TicketEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketEventCreateBulk.OnConflict
// documentation for more info.
func (u *TicketEventUpsertBulk) Update(set func(*TicketEventUpsert)) *TicketEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketEventUpsertBulk) SetTicketID(v int64) *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketEventUpsertBulk) UpdateTicketID() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateTicketID()
	})
}

// SetActorID sets the "actor_id" field.
func (u *TicketEventUpsertBulk) SetActorID(v int64) *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetActorID(v)
	})
}

// UpdateActorID sets the "actor_id" field to the value that was provided on create.
func (u *TicketEventUpsertBulk) UpdateActorID() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateActorID()
	})
}

// ClearActorID clears the value of the "actor_id" field.
func (u *TicketEventUpsertBulk) ClearActorID() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.ClearActorID()
	})
}

// SetActorRole sets the "actor_role" field.
func (u *TicketEventUpsertBulk) SetActorRole(v string) *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetActorRole(v)
	})
}

// UpdateActorRole sets the "actor_role" field to the value that was provided on create.
func (u *TicketEventUpsertBulk) UpdateActorRole() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateActorRole()
	})
}

// SetEventType sets the "event_type" field.
func (u *TicketEventUpsertBulk) SetEventType(v string) *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *TicketEventUpsertBulk) UpdateEventType() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateEventType()
	})
}

// SetFromStatus sets the "from_status" field.
func (u *TicketEventUpsertBulk) SetFromStatus(v string) *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetFromStatus(v)
	})
}

// UpdateFromStatus sets the "from_status" field to the value that was provided on create.
func (u *TicketEventUpsertBulk) UpdateFromStatus() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateFromStatus()
	})
}

// ClearFromStatus clears the value of the "from_status" field.
func (u *TicketEventUpsertBulk) ClearFromStatus() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.ClearFromStatus()
	})
}

// SetToStatus sets the "to_status" field.
func (u *TicketEventUpsertBulk) SetToStatus(v string) *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetToStatus(v)
	})
}

// UpdateToStatus sets the "to_status" field to the value that was provided on create.
func (u *TicketEventUpsertBulk) UpdateToStatus() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateToStatus()
	})
}

// ClearToStatus clears the value of the "to_status" field.
func (u *TicketEventUpsertBulk) ClearToStatus() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.ClearToStatus()
	})
}

// SetPayload sets the "payload" field.
func (u *TicketEventUpsertBulk) SetPayload(v map[string]interface{}) *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *TicketEventUpsertBulk) UpdatePayload() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdatePayload()
	})
}

// SetVisibility sets the "visibility" field.
func (u *TicketEventUpsertBulk) SetVisibility(v string) *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketEventUpsertBulk) UpdateVisibility() *TicketEventUpsertBulk {
	return u.Update(func(s *TicketEventUpsert) {
		s.UpdateVisibility()
	})
}

// Exec executes the query.
func (u *TicketEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
