// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketEvent is the model entity for the TicketEvent schema.
type TicketEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID int64 `json:"ticket_id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID *int64 `json:"actor_id,omitempty"`
	// ActorRole holds the value of the "actor_role" field.
	ActorRole string `json:"actor_role,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// FromStatus holds the value of the "from_status" field.
	FromStatus *string `json:"from_status,omitempty"`
	// ToStatus holds the value of the "to_status" field.
	ToStatus *string `json:"to_status,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility string `json:"visibility,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketEventQuery when eager-loading is set.
	Edges        TicketEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketEventEdges holds the relations/edges for other nodes in the graph.
type TicketEventEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *Ticket `json:"ticket,omitempty"`
	// Actor holds the value of the actor edge.
	Actor *User `json:"actor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEventEdges) TicketOrErr() (*Ticket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// ActorOrErr returns the Actor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEventEdges) ActorOrErr() (*User, error) {
	if e.Actor != nil {
		return e.Actor, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "actor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketevent.FieldPayload:
			values[i] = new([]byte)
		case ticketevent.FieldID, ticketevent.FieldTicketID, ticketevent.FieldActorID:
			values[i] = new(sql.NullInt64)
		case ticketevent.FieldActorRole, ticketevent.FieldEventType, ticketevent.FieldFromStatus, ticketevent.FieldToStatus, ticketevent.FieldVisibility:
			values[i] = new(sql.NullString)
		case ticketevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketEvent fields.
func (_m *TicketEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ticketevent.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = value.Int64
			}
		case ticketevent.FieldActorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = new(int64)
				*_m.ActorID = value.Int64
			}
		case ticketevent.FieldActorRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_role", values[i])
			} else if value.Valid {
				_m.ActorRole = value.String
			}
		case ticketevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case ticketevent.FieldFromStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_status", values[i])
			} else if value.Valid {
				_m.FromStatus = new(string)
				*_m.FromStatus = value.String
			}
		case ticketevent.FieldToStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_status", values[i])
			} else if value.Valid {
				_m.ToStatus = new(string)
				*_m.ToStatus = value.String
			}
		case ticketevent.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case ticketevent.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = value.String
			}
		case ticketevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketEvent.
// This includes values selected through modifiers, order, etc.
func (_m *TicketEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the TicketEvent entity.
func (_m *TicketEvent) QueryTicket() *TicketQuery {
	return NewTicketEventClient(_m.config).QueryTicket(_m)
}

// QueryActor queries the "actor" edge of the TicketEvent entity.
func (_m *TicketEvent) QueryActor() *UserQuery {
	return NewTicketEventClient(_m.config).QueryActor(_m)
}

// Update returns a builder for updating this TicketEvent.
// Note that you need to call TicketEvent.Unwrap() before calling this method if this TicketEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketEvent) Update() *TicketEventUpdateOne {
	return NewTicketEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketEvent) Unwrap() *TicketEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TicketEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketEvent) String() string {
	var builder strings.Builder
	builder.WriteString("TicketEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	if v := _m.ActorID; v != nil {
		builder.WriteString("actor_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("actor_role=")
	builder.WriteString(_m.ActorRole)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	if v := _m.FromStatus; v != nil {
		builder.WriteString("from_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ToStatus; v != nil {
		builder.WriteString("to_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(_m.Visibility)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TicketEvents is a parsable slice of TicketEvent.
type TicketEvents []*TicketEvent
