// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/ticketevent"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketCreate is the builder for creating a Ticket entity.
type TicketCreate struct {
	config
	mutation *TicketMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketCreate) SetCreatedAt(v time.Time) *TicketCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableCreatedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TicketCreate) SetUpdatedAt(v time.Time) *TicketCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableUpdatedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTicketNo sets the "ticket_no" field.
func (_c *TicketCreate) SetTicketNo(v string) *TicketCreate {
	_c.mutation.SetTicketNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TicketCreate) SetUserID(v int64) *TicketCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableUserID(v *int64) *TicketCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetRequesterEmail sets the "requester_email" field.
func (_c *TicketCreate) SetRequesterEmail(v string) *TicketCreate {
	_c.mutation.SetRequesterEmail(v)
	return _c
}

// SetNillableRequesterEmail sets the "requester_email" field if the given value is not nil.
func (_c *TicketCreate) SetNillableRequesterEmail(v *string) *TicketCreate {
	if v != nil {
		_c.SetRequesterEmail(*v)
	}
	return _c
}

// SetRequesterUsername sets the "requester_username" field.
func (_c *TicketCreate) SetRequesterUsername(v string) *TicketCreate {
	_c.mutation.SetRequesterUsername(v)
	return _c
}

// SetNillableRequesterUsername sets the "requester_username" field if the given value is not nil.
func (_c *TicketCreate) SetNillableRequesterUsername(v *string) *TicketCreate {
	if v != nil {
		_c.SetRequesterUsername(*v)
	}
	return _c
}

// SetSubject sets the "subject" field.
func (_c *TicketCreate) SetSubject(v string) *TicketCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *TicketCreate) SetCategory(v string) *TicketCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetImpact sets the "impact" field.
func (_c *TicketCreate) SetImpact(v string) *TicketCreate {
	_c.mutation.SetImpact(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *TicketCreate) SetPriority(v string) *TicketCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *TicketCreate) SetNillablePriority(v *string) *TicketCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TicketCreate) SetStatus(v string) *TicketCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TicketCreate) SetNillableStatus(v *string) *TicketCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAssigneeID sets the "assignee_id" field.
func (_c *TicketCreate) SetAssigneeID(v int64) *TicketCreate {
	_c.mutation.SetAssigneeID(v)
	return _c
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableAssigneeID(v *int64) *TicketCreate {
	if v != nil {
		_c.SetAssigneeID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *TicketCreate) SetRequestID(v string) *TicketCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableRequestID(v *string) *TicketCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *TicketCreate) SetUsageLogID(v int64) *TicketCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableUsageLogID(v *int64) *TicketCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *TicketCreate) SetAPIKeyID(v int64) *TicketCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableAPIKeyID(v *int64) *TicketCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetAPIKeyName sets the "api_key_name" field.
func (_c *TicketCreate) SetAPIKeyName(v string) *TicketCreate {
	_c.mutation.SetAPIKeyName(v)
	return _c
}

// SetNillableAPIKeyName sets the "api_key_name" field if the given value is not nil.
func (_c *TicketCreate) SetNillableAPIKeyName(v *string) *TicketCreate {
	if v != nil {
		_c.SetAPIKeyName(*v)
	}
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *TicketCreate) SetPaymentOrderID(v int64) *TicketCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillablePaymentOrderID(v *int64) *TicketCreate {
	if v != nil {
		_c.SetPaymentOrderID(*v)
	}
	return _c
}

// SetPaymentOrderNo sets the "payment_order_no" field.
func (_c *TicketCreate) SetPaymentOrderNo(v string) *TicketCreate {
	_c.mutation.SetPaymentOrderNo(v)
	return _c
}

// SetNillablePaymentOrderNo sets the "payment_order_no" field if the given value is not nil.
func (_c *TicketCreate) SetNillablePaymentOrderNo(v *string) *TicketCreate {
	if v != nil {
		_c.SetPaymentOrderNo(*v)
	}
	return _c
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (_c *TicketCreate) SetUserSubscriptionID(v int64) *TicketCreate {
	_c.mutation.SetUserSubscriptionID(v)
	return _c
}

// SetNillableUserSubscriptionID sets the "user_subscription_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableUserSubscriptionID(v *int64) *TicketCreate {
	if v != nil {
		_c.SetUserSubscriptionID(*v)
	}
	return _c
}

// SetSubscriptionName sets the "subscription_name" field.
func (_c *TicketCreate) SetSubscriptionName(v string) *TicketCreate {
	_c.mutation.SetSubscriptionName(v)
	return _c
}

// SetNillableSubscriptionName sets the "subscription_name" field if the given value is not nil.
func (_c *TicketCreate) SetNillableSubscriptionName(v *string) *TicketCreate {
	if v != nil {
		_c.SetSubscriptionName(*v)
	}
	return _c
}

// SetLastPublicMessageAt sets the "last_public_message_at" field.
func (_c *TicketCreate) SetLastPublicMessageAt(v time.Time) *TicketCreate {
	_c.mutation.SetLastPublicMessageAt(v)
	return _c
}

// SetNillableLastPublicMessageAt sets the "last_public_message_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableLastPublicMessageAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetLastPublicMessageAt(*v)
	}
	return _c
}

// SetLastActivityAt sets the "last_activity_at" field.
func (_c *TicketCreate) SetLastActivityAt(v time.Time) *TicketCreate {
	_c.mutation.SetLastActivityAt(v)
	return _c
}

// SetNillableLastActivityAt sets the "last_activity_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableLastActivityAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetLastActivityAt(*v)
	}
	return _c
}

// SetActionRequiredSince sets the "action_required_since" field.
func (_c *TicketCreate) SetActionRequiredSince(v time.Time) *TicketCreate {
	_c.mutation.SetActionRequiredSince(v)
	return _c
}

// SetNillableActionRequiredSince sets the "action_required_since" field if the given value is not nil.
func (_c *TicketCreate) SetNillableActionRequiredSince(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetActionRequiredSince(*v)
	}
	return _c
}

// SetUserNotificationSeq sets the "user_notification_seq" field.
func (_c *TicketCreate) SetUserNotificationSeq(v int64) *TicketCreate {
	_c.mutation.SetUserNotificationSeq(v)
	return _c
}

// SetNillableUserNotificationSeq sets the "user_notification_seq" field if the given value is not nil.
func (_c *TicketCreate) SetNillableUserNotificationSeq(v *int64) *TicketCreate {
	if v != nil {
		_c.SetUserNotificationSeq(*v)
	}
	return _c
}

// SetUserLastReadSeq sets the "user_last_read_seq" field.
func (_c *TicketCreate) SetUserLastReadSeq(v int64) *TicketCreate {
	_c.mutation.SetUserLastReadSeq(v)
	return _c
}

// SetNillableUserLastReadSeq sets the "user_last_read_seq" field if the given value is not nil.
func (_c *TicketCreate) SetNillableUserLastReadSeq(v *int64) *TicketCreate {
	if v != nil {
		_c.SetUserLastReadSeq(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *TicketCreate) SetResolvedAt(v time.Time) *TicketCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableResolvedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetReopenDeadline sets the "reopen_deadline" field.
func (_c *TicketCreate) SetReopenDeadline(v time.Time) *TicketCreate {
	_c.mutation.SetReopenDeadline(v)
	return _c
}

// SetNillableReopenDeadline sets the "reopen_deadline" field if the given value is not nil.
func (_c *TicketCreate) SetNillableReopenDeadline(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetReopenDeadline(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *TicketCreate) SetClosedAt(v time.Time) *TicketCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableClosedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *TicketCreate) SetVersion(v int64) *TicketCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *TicketCreate) SetNillableVersion(v *int64) *TicketCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetRequesterID sets the "requester" edge to the User entity by ID.
func (_c *TicketCreate) SetRequesterID(id int64) *TicketCreate {
	_c.mutation.SetRequesterID(id)
	return _c
}

// SetNillableRequesterID sets the "requester" edge to the User entity by ID if the given value is not nil.
func (_c *TicketCreate) SetNillableRequesterID(id *int64) *TicketCreate {
	if id != nil {
		_c = _c.SetRequesterID(*id)
	}
	return _c
}

// SetRequester sets the "requester" edge to the User entity.
func (_c *TicketCreate) SetRequester(v *User) *TicketCreate {
	return _c.SetRequesterID(v.ID)
}

// SetAssignee sets the "assignee" edge to the User entity.
func (_c *TicketCreate) SetAssignee(v *User) *TicketCreate {
	return _c.SetAssigneeID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the TicketMessage entity by IDs.
func (_c *TicketCreate) AddMessageIDs(ids ...int64) *TicketCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the TicketMessage entity.
func (_c *TicketCreate) AddMessages(v ...*TicketMessage) *TicketCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// AddEventIDs adds the "events" edge to the TicketEvent entity by IDs.
func (_c *TicketCreate) AddEventIDs(ids ...int64) *TicketCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the TicketEvent entity.
func (_c *TicketCreate) AddEvents(v ...*TicketEvent) *TicketCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the TicketAttachment entity by IDs.
func (_c *TicketCreate) AddAttachmentIDs(ids ...int64) *TicketCreate {
	_c.mutation.AddAttachmentIDs(ids...)
	return _c
}

// AddAttachments adds the "attachments" edges to the TicketAttachment entity.
func (_c *TicketCreate) AddAttachments(v ...*TicketAttachment) *TicketCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttachmentIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_c *TicketCreate) Mutation() *TicketMutation {
	return _c.mutation
}

// Save creates the Ticket in the database.
func (_c *TicketCreate) Save(ctx context.Context) (*Ticket, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketCreate) SaveX(ctx context.Context) *Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticket.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ticket.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RequesterEmail(); !ok {
		v := ticket.DefaultRequesterEmail
		_c.mutation.SetRequesterEmail(v)
	}
	if _, ok := _c.mutation.RequesterUsername(); !ok {
		v := ticket.DefaultRequesterUsername
		_c.mutation.SetRequesterUsername(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := ticket.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ticket.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := ticket.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.APIKeyName(); !ok {
		v := ticket.DefaultAPIKeyName
		_c.mutation.SetAPIKeyName(v)
	}
	if _, ok := _c.mutation.PaymentOrderNo(); !ok {
		v := ticket.DefaultPaymentOrderNo
		_c.mutation.SetPaymentOrderNo(v)
	}
	if _, ok := _c.mutation.SubscriptionName(); !ok {
		v := ticket.DefaultSubscriptionName
		_c.mutation.SetSubscriptionName(v)
	}
	if _, ok := _c.mutation.LastPublicMessageAt(); !ok {
		v := ticket.DefaultLastPublicMessageAt()
		_c.mutation.SetLastPublicMessageAt(v)
	}
	if _, ok := _c.mutation.LastActivityAt(); !ok {
		v := ticket.DefaultLastActivityAt()
		_c.mutation.SetLastActivityAt(v)
	}
	if _, ok := _c.mutation.UserNotificationSeq(); !ok {
		v := ticket.DefaultUserNotificationSeq
		_c.mutation.SetUserNotificationSeq(v)
	}
	if _, ok := _c.mutation.UserLastReadSeq(); !ok {
		v := ticket.DefaultUserLastReadSeq
		_c.mutation.SetUserLastReadSeq(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := ticket.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ticket.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ticket.updated_at"`)}
	}
	if _, ok := _c.mutation.TicketNo(); !ok {
		return &ValidationError{Name: "ticket_no", err: errors.New(`ent: missing required field "Ticket.ticket_no"`)}
	}
	if v, ok := _c.mutation.TicketNo(); ok {
		if err := ticket.TicketNoValidator(v); err != nil {
			return &ValidationError{Name: "ticket_no", err: fmt.Errorf(`ent: validator failed for field "Ticket.ticket_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequesterEmail(); !ok {
		return &ValidationError{Name: "requester_email", err: errors.New(`ent: missing required field "Ticket.requester_email"`)}
	}
	if v, ok := _c.mutation.RequesterEmail(); ok {
		if err := ticket.RequesterEmailValidator(v); err != nil {
			return &ValidationError{Name: "requester_email", err: fmt.Errorf(`ent: validator failed for field "Ticket.requester_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequesterUsername(); !ok {
		return &ValidationError{Name: "requester_username", err: errors.New(`ent: missing required field "Ticket.requester_username"`)}
	}
	if v, ok := _c.mutation.RequesterUsername(); ok {
		if err := ticket.RequesterUsernameValidator(v); err != nil {
			return &ValidationError{Name: "requester_username", err: fmt.Errorf(`ent: validator failed for field "Ticket.requester_username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Ticket.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := ticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Ticket.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Ticket.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := ticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Ticket.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Impact(); !ok {
		return &ValidationError{Name: "impact", err: errors.New(`ent: missing required field "Ticket.impact"`)}
	}
	if v, ok := _c.mutation.Impact(); ok {
		if err := ticket.ImpactValidator(v); err != nil {
			return &ValidationError{Name: "impact", err: fmt.Errorf(`ent: validator failed for field "Ticket.impact": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Ticket.priority"`)}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := ticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Ticket.priority": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Ticket.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Ticket.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "Ticket.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := ticket.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "Ticket.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyName(); !ok {
		return &ValidationError{Name: "api_key_name", err: errors.New(`ent: missing required field "Ticket.api_key_name"`)}
	}
	if v, ok := _c.mutation.APIKeyName(); ok {
		if err := ticket.APIKeyNameValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name", err: fmt.Errorf(`ent: validator failed for field "Ticket.api_key_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentOrderNo(); !ok {
		return &ValidationError{Name: "payment_order_no", err: errors.New(`ent: missing required field "Ticket.payment_order_no"`)}
	}
	if v, ok := _c.mutation.PaymentOrderNo(); ok {
		if err := ticket.PaymentOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "payment_order_no", err: fmt.Errorf(`ent: validator failed for field "Ticket.payment_order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriptionName(); !ok {
		return &ValidationError{Name: "subscription_name", err: errors.New(`ent: missing required field "Ticket.subscription_name"`)}
	}
	if v, ok := _c.mutation.SubscriptionName(); ok {
		if err := ticket.SubscriptionNameValidator(v); err != nil {
			return &ValidationError{Name: "subscription_name", err: fmt.Errorf(`ent: validator failed for field "Ticket.subscription_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastPublicMessageAt(); !ok {
		return &ValidationError{Name: "last_public_message_at", err: errors.New(`ent: missing required field "Ticket.last_public_message_at"`)}
	}
	if _, ok := _c.mutation.LastActivityAt(); !ok {
		return &ValidationError{Name: "last_activity_at", err: errors.New(`ent: missing required field "Ticket.last_activity_at"`)}
	}
	if _, ok := _c.mutation.UserNotificationSeq(); !ok {
		return &ValidationError{Name: "user_notification_seq", err: errors.New(`ent: missing required field "Ticket.user_notification_seq"`)}
	}
	if v, ok := _c.mutation.UserNotificationSeq(); ok {
		if err := ticket.UserNotificationSeqValidator(v); err != nil {
			return &ValidationError{Name: "user_notification_seq", err: fmt.Errorf(`ent: validator failed for field "Ticket.user_notification_seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserLastReadSeq(); !ok {
		return &ValidationError{Name: "user_last_read_seq", err: errors.New(`ent: missing required field "Ticket.user_last_read_seq"`)}
	}
	if v, ok := _c.mutation.UserLastReadSeq(); ok {
		if err := ticket.UserLastReadSeqValidator(v); err != nil {
			return &ValidationError{Name: "user_last_read_seq", err: fmt.Errorf(`ent: validator failed for field "Ticket.user_last_read_seq": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Ticket.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := ticket.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Ticket.version": %w`, err)}
		}
	}
	return nil
}

func (_c *TicketCreate) sqlSave(ctx context.Context) (*Ticket, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketCreate) createSpec() (*Ticket, *sqlgraph.CreateSpec) {
	var (
		_node = &Ticket{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticket.Table, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticket.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ticket.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TicketNo(); ok {
		_spec.SetField(ticket.FieldTicketNo, field.TypeString, value)
		_node.TicketNo = value
	}
	if value, ok := _c.mutation.RequesterEmail(); ok {
		_spec.SetField(ticket.FieldRequesterEmail, field.TypeString, value)
		_node.RequesterEmail = value
	}
	if value, ok := _c.mutation.RequesterUsername(); ok {
		_spec.SetField(ticket.FieldRequesterUsername, field.TypeString, value)
		_node.RequesterUsername = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(ticket.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(ticket.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Impact(); ok {
		_spec.SetField(ticket.FieldImpact, field.TypeString, value)
		_node.Impact = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(ticket.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(ticket.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(ticket.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(ticket.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.APIKeyName(); ok {
		_spec.SetField(ticket.FieldAPIKeyName, field.TypeString, value)
		_node.APIKeyName = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(ticket.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = &value
	}
	if value, ok := _c.mutation.PaymentOrderNo(); ok {
		_spec.SetField(ticket.FieldPaymentOrderNo, field.TypeString, value)
		_node.PaymentOrderNo = value
	}
	if value, ok := _c.mutation.UserSubscriptionID(); ok {
		_spec.SetField(ticket.FieldUserSubscriptionID, field.TypeInt64, value)
		_node.UserSubscriptionID = &value
	}
	if value, ok := _c.mutation.SubscriptionName(); ok {
		_spec.SetField(ticket.FieldSubscriptionName, field.TypeString, value)
		_node.SubscriptionName = value
	}
	if value, ok := _c.mutation.LastPublicMessageAt(); ok {
		_spec.SetField(ticket.FieldLastPublicMessageAt, field.TypeTime, value)
		_node.LastPublicMessageAt = value
	}
	if value, ok := _c.mutation.LastActivityAt(); ok {
		_spec.SetField(ticket.FieldLastActivityAt, field.TypeTime, value)
		_node.LastActivityAt = value
	}
	if value, ok := _c.mutation.ActionRequiredSince(); ok {
		_spec.SetField(ticket.FieldActionRequiredSince, field.TypeTime, value)
		_node.ActionRequiredSince = &value
	}
	if value, ok := _c.mutation.UserNotificationSeq(); ok {
		_spec.SetField(ticket.FieldUserNotificationSeq, field.TypeInt64, value)
		_node.UserNotificationSeq = value
	}
	if value, ok := _c.mutation.UserLastReadSeq(); ok {
		_spec.SetField(ticket.FieldUserLastReadSeq, field.TypeInt64, value)
		_node.UserLastReadSeq = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(ticket.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if value, ok := _c.mutation.ReopenDeadline(); ok {
		_spec.SetField(ticket.FieldReopenDeadline, field.TypeTime, value)
		_node.ReopenDeadline = &value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(ticket.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(ticket.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if nodes := _c.mutation.RequesterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.RequesterTable,
			Columns: []string{ticket.RequesterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssigneeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticket.AssigneeTable,
			Columns: []string{ticket.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssigneeID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.MessagesTable,
			Columns: []string{ticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.EventsTable,
			Columns: []string{ticket.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.AttachmentsTable,
			Columns: []string{ticket.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ticket.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketCreate) OnConflict(opts ...sql.ConflictOption) *TicketUpsertOne {
	_c.conflict = opts
	return &TicketUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketCreate) OnConflictColumns(columns ...string) *TicketUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketUpsertOne{
		create: _c,
	}
}

type (
	// TicketUpsertOne is the builder for "upsert"-ing
	//  one Ticket node.
	TicketUpsertOne struct {
		create *TicketCreate
	}

	// TicketUpsert is the "OnConflict" setter.
	TicketUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketUpsert) SetUpdatedAt(v time.Time) *TicketUpsert {
	u.Set(ticket.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketUpsert) UpdateUpdatedAt() *TicketUpsert {
	u.SetExcluded(ticket.FieldUpdatedAt)
	return u
}

// SetTicketNo sets the "ticket_no" field.
func (u *TicketUpsert) SetTicketNo(v string) *TicketUpsert {
	u.Set(ticket.FieldTicketNo, v)
	return u
}

// UpdateTicketNo sets the "ticket_no" field to the value that was provided on create.
func (u *TicketUpsert) UpdateTicketNo() *TicketUpsert {
	u.SetExcluded(ticket.FieldTicketNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TicketUpsert) SetUserID(v int64) *TicketUpsert {
	u.Set(ticket.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateUserID() *TicketUpsert {
	u.SetExcluded(ticket.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *TicketUpsert) ClearUserID() *TicketUpsert {
	u.SetNull(ticket.FieldUserID)
	return u
}

// SetRequesterEmail sets the "requester_email" field.
func (u *TicketUpsert) SetRequesterEmail(v string) *TicketUpsert {
	u.Set(ticket.FieldRequesterEmail, v)
	return u
}

// UpdateRequesterEmail sets the "requester_email" field to the value that was provided on create.
func (u *TicketUpsert) UpdateRequesterEmail() *TicketUpsert {
	u.SetExcluded(ticket.FieldRequesterEmail)
	return u
}

// SetRequesterUsername sets the "requester_username" field.
func (u *TicketUpsert) SetRequesterUsername(v string) *TicketUpsert {
	u.Set(ticket.FieldRequesterUsername, v)
	return u
}

// UpdateRequesterUsername sets the "requester_username" field to the value that was provided on create.
func (u *TicketUpsert) UpdateRequesterUsername() *TicketUpsert {
	u.SetExcluded(ticket.FieldRequesterUsername)
	return u
}

// SetSubject sets the "subject" field.
func (u *TicketUpsert) SetSubject(v string) *TicketUpsert {
	u.Set(ticket.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *TicketUpsert) UpdateSubject() *TicketUpsert {
	u.SetExcluded(ticket.FieldSubject)
	return u
}

// SetCategory sets the "category" field.
func (u *TicketUpsert) SetCategory(v string) *TicketUpsert {
	u.Set(ticket.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TicketUpsert) UpdateCategory() *TicketUpsert {
	u.SetExcluded(ticket.FieldCategory)
	return u
}

// SetImpact sets the "impact" field.
func (u *TicketUpsert) SetImpact(v string) *TicketUpsert {
	u.Set(ticket.FieldImpact, v)
	return u
}

// UpdateImpact sets the "impact" field to the value that was provided on create.
func (u *TicketUpsert) UpdateImpact() *TicketUpsert {
	u.SetExcluded(ticket.FieldImpact)
	return u
}

// SetPriority sets the "priority" field.
func (u *TicketUpsert) SetPriority(v string) *TicketUpsert {
	u.Set(ticket.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *TicketUpsert) UpdatePriority() *TicketUpsert {
	u.SetExcluded(ticket.FieldPriority)
	return u
}

// SetStatus sets the "status" field.
func (u *TicketUpsert) SetStatus(v string) *TicketUpsert {
	u.Set(ticket.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TicketUpsert) UpdateStatus() *TicketUpsert {
	u.SetExcluded(ticket.FieldStatus)
	return u
}

// SetAssigneeID sets the "assignee_id" field.
func (u *TicketUpsert) SetAssigneeID(v int64) *TicketUpsert {
	u.Set(ticket.FieldAssigneeID, v)
	return u
}

// UpdateAssigneeID sets the "assignee_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateAssigneeID() *TicketUpsert {
	u.SetExcluded(ticket.FieldAssigneeID)
	return u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (u *TicketUpsert) ClearAssigneeID() *TicketUpsert {
	u.SetNull(ticket.FieldAssigneeID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *TicketUpsert) SetRequestID(v string) *TicketUpsert {
	u.Set(ticket.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateRequestID() *TicketUpsert {
	u.SetExcluded(ticket.FieldRequestID)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *TicketUpsert) SetUsageLogID(v int64) *TicketUpsert {
	u.Set(ticket.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateUsageLogID() *TicketUpsert {
	u.SetExcluded(ticket.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *TicketUpsert) AddUsageLogID(v int64) *TicketUpsert {
	u.Add(ticket.FieldUsageLogID, v)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *TicketUpsert) ClearUsageLogID() *TicketUpsert {
	u.SetNull(ticket.FieldUsageLogID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *TicketUpsert) SetAPIKeyID(v int64) *TicketUpsert {
	u.Set(ticket.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateAPIKeyID() *TicketUpsert {
	u.SetExcluded(ticket.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *TicketUpsert) AddAPIKeyID(v int64) *TicketUpsert {
	u.Add(ticket.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *TicketUpsert) ClearAPIKeyID() *TicketUpsert {
	u.SetNull(ticket.FieldAPIKeyID)
	return u
}

// SetAPIKeyName sets the "api_key_name" field.
func (u *TicketUpsert) SetAPIKeyName(v string) *TicketUpsert {
	u.Set(ticket.FieldAPIKeyName, v)
	return u
}

// UpdateAPIKeyName sets the "api_key_name" field to the value that was provided on create.
func (u *TicketUpsert) UpdateAPIKeyName() *TicketUpsert {
	u.SetExcluded(ticket.FieldAPIKeyName)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *TicketUpsert) SetPaymentOrderID(v int64) *TicketUpsert {
	u.Set(ticket.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdatePaymentOrderID() *TicketUpsert {
	u.SetExcluded(ticket.FieldPaymentOrderID)
	return u
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *TicketUpsert) AddPaymentOrderID(v int64) *TicketUpsert {
	u.Add(ticket.FieldPaymentOrderID, v)
	return u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *TicketUpsert) ClearPaymentOrderID() *TicketUpsert {
	u.SetNull(ticket.FieldPaymentOrderID)
	return u
}

// SetPaymentOrderNo sets the "payment_order_no" field.
func (u *TicketUpsert) SetPaymentOrderNo(v string) *TicketUpsert {
	u.Set(ticket.FieldPaymentOrderNo, v)
	return u
}

// UpdatePaymentOrderNo sets the "payment_order_no" field to the value that was provided on create.
func (u *TicketUpsert) UpdatePaymentOrderNo() *TicketUpsert {
	u.SetExcluded(ticket.FieldPaymentOrderNo)
	return u
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *TicketUpsert) SetUserSubscriptionID(v int64) *TicketUpsert {
	u.Set(ticket.FieldUserSubscriptionID, v)
	return u
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateUserSubscriptionID() *TicketUpsert {
	u.SetExcluded(ticket.FieldUserSubscriptionID)
	return u
}

// AddUserSubscriptionID adds v to the "user_subscription_id" field.
func (u *TicketUpsert) AddUserSubscriptionID(v int64) *TicketUpsert {
	u.Add(ticket.FieldUserSubscriptionID, v)
	return u
}

// ClearUserSubscriptionID clears the value of the "user_subscription_id" field.
func (u *TicketUpsert) ClearUserSubscriptionID() *TicketUpsert {
	u.SetNull(ticket.FieldUserSubscriptionID)
	return u
}

// SetSubscriptionName sets the "subscription_name" field.
func (u *TicketUpsert) SetSubscriptionName(v string) *TicketUpsert {
	u.Set(ticket.FieldSubscriptionName, v)
	return u
}

// UpdateSubscriptionName sets the "subscription_name" field to the value that was provided on create.
func (u *TicketUpsert) UpdateSubscriptionName() *TicketUpsert {
	u.SetExcluded(ticket.FieldSubscriptionName)
	return u
}

// SetLastPublicMessageAt sets the "last_public_message_at" field.
func (u *TicketUpsert) SetLastPublicMessageAt(v time.Time) *TicketUpsert {
	u.Set(ticket.FieldLastPublicMessageAt, v)
	return u
}

// UpdateLastPublicMessageAt sets the "last_public_message_at" field to the value that was provided on create.
func (u *TicketUpsert) UpdateLastPublicMessageAt() *TicketUpsert {
	u.SetExcluded(ticket.FieldLastPublicMessageAt)
	return u
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *TicketUpsert) SetLastActivityAt(v time.Time) *TicketUpsert {
	u.Set(ticket.FieldLastActivityAt, v)
	return u
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *TicketUpsert) UpdateLastActivityAt() *TicketUpsert {
	u.SetExcluded(ticket.FieldLastActivityAt)
	return u
}

// SetActionRequiredSince sets the "action_required_since" field.
func (u *TicketUpsert) SetActionRequiredSince(v time.Time) *TicketUpsert {
	u.Set(ticket.FieldActionRequiredSince, v)
	return u
}

// UpdateActionRequiredSince sets the "action_required_since" field to the value that was provided on create.
func (u *TicketUpsert) UpdateActionRequiredSince() *TicketUpsert {
	u.SetExcluded(ticket.FieldActionRequiredSince)
	return u
}

// ClearActionRequiredSince clears the value of the "action_required_since" field.
func (u *TicketUpsert) ClearActionRequiredSince() *TicketUpsert {
	u.SetNull(ticket.FieldActionRequiredSince)
	return u
}

// SetUserNotificationSeq sets the "user_notification_seq" field.
func (u *TicketUpsert) SetUserNotificationSeq(v int64) *TicketUpsert {
	u.Set(ticket.FieldUserNotificationSeq, v)
	return u
}

// UpdateUserNotificationSeq sets the "user_notification_seq" field to the value that was provided on create.
func (u *TicketUpsert) UpdateUserNotificationSeq() *TicketUpsert {
	u.SetExcluded(ticket.FieldUserNotificationSeq)
	return u
}

// AddUserNotificationSeq adds v to the "user_notification_seq" field.
func (u *TicketUpsert) AddUserNotificationSeq(v int64) *TicketUpsert {
	u.Add(ticket.FieldUserNotificationSeq, v)
	return u
}

// SetUserLastReadSeq sets the "user_last_read_seq" field.
func (u *TicketUpsert) SetUserLastReadSeq(v int64) *TicketUpsert {
	u.Set(ticket.FieldUserLastReadSeq, v)
	return u
}

// UpdateUserLastReadSeq sets the "user_last_read_seq" field to the value that was provided on create.
func (u *TicketUpsert) UpdateUserLastReadSeq() *TicketUpsert {
	u.SetExcluded(ticket.FieldUserLastReadSeq)
	return u
}

// AddUserLastReadSeq adds v to the "user_last_read_seq" field.
func (u *TicketUpsert) AddUserLastReadSeq(v int64) *TicketUpsert {
	u.Add(ticket.FieldUserLastReadSeq, v)
	return u
}

// SetResolvedAt sets the "resolved_at" field.
func (u *TicketUpsert) SetResolvedAt(v time.Time) *TicketUpsert {
	u.Set(ticket.FieldResolvedAt, v)
	return u
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *TicketUpsert) UpdateResolvedAt() *TicketUpsert {
	u.SetExcluded(ticket.FieldResolvedAt)
	return u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *TicketUpsert) ClearResolvedAt() *TicketUpsert {
	u.SetNull(ticket.FieldResolvedAt)
	return u
}

// SetReopenDeadline sets the "reopen_deadline" field.
func (u *TicketUpsert) SetReopenDeadline(v time.Time) *TicketUpsert {
	u.Set(ticket.FieldReopenDeadline, v)
	return u
}

// UpdateReopenDeadline sets the "reopen_deadline" field to the value that was provided on create.
func (u *TicketUpsert) UpdateReopenDeadline() *TicketUpsert {
	u.SetExcluded(ticket.FieldReopenDeadline)
	return u
}

// ClearReopenDeadline clears the value of the "reopen_deadline" field.
func (u *TicketUpsert) ClearReopenDeadline() *TicketUpsert {
	u.SetNull(ticket.FieldReopenDeadline)
	return u
}

// SetClosedAt sets the "closed_at" field.
func (u *TicketUpsert) SetClosedAt(v time.Time) *TicketUpsert {
	u.Set(ticket.FieldClosedAt, v)
	return u
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *TicketUpsert) UpdateClosedAt() *TicketUpsert {
	u.SetExcluded(ticket.FieldClosedAt)
	return u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *TicketUpsert) ClearClosedAt() *TicketUpsert {
	u.SetNull(ticket.FieldClosedAt)
	return u
}

// SetVersion sets the "version" field.
func (u *TicketUpsert) SetVersion(v int64) *TicketUpsert {
	u.Set(ticket.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *TicketUpsert) UpdateVersion() *TicketUpsert {
	u.SetExcluded(ticket.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *TicketUpsert) AddVersion(v int64) *TicketUpsert {
	u.Add(ticket.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketUpsertOne) UpdateNewValues() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ticket.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketUpsertOne) Ignore() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketUpsertOne) DoNothing() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketCreate.OnConflict
// documentation for more info.
func (u *TicketUpsertOne) Update(set func(*TicketUpsert)) *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketUpsertOne) SetUpdatedAt(v time.Time) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateUpdatedAt() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTicketNo sets the "ticket_no" field.
func (u *TicketUpsertOne) SetTicketNo(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetTicketNo(v)
	})
}

// UpdateTicketNo sets the "ticket_no" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateTicketNo() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateTicketNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *TicketUpsertOne) SetUserID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateUserID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *TicketUpsertOne) ClearUserID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearUserID()
	})
}

// SetRequesterEmail sets the "requester_email" field.
func (u *TicketUpsertOne) SetRequesterEmail(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetRequesterEmail(v)
	})
}

// UpdateRequesterEmail sets the "requester_email" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateRequesterEmail() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRequesterEmail()
	})
}

// SetRequesterUsername sets the "requester_username" field.
func (u *TicketUpsertOne) SetRequesterUsername(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetRequesterUsername(v)
	})
}

// UpdateRequesterUsername sets the "requester_username" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateRequesterUsername() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRequesterUsername()
	})
}

// SetSubject sets the "subject" field.
func (u *TicketUpsertOne) SetSubject(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateSubject() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateSubject()
	})
}

// SetCategory sets the "category" field.
func (u *TicketUpsertOne) SetCategory(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateCategory() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateCategory()
	})
}

// SetImpact sets the "impact" field.
func (u *TicketUpsertOne) SetImpact(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetImpact(v)
	})
}

// UpdateImpact sets the "impact" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateImpact() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateImpact()
	})
}

// SetPriority sets the "priority" field.
func (u *TicketUpsertOne) SetPriority(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdatePriority() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePriority()
	})
}

// SetStatus sets the "status" field.
func (u *TicketUpsertOne) SetStatus(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateStatus() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateStatus()
	})
}

// SetAssigneeID sets the "assignee_id" field.
func (u *TicketUpsertOne) SetAssigneeID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetAssigneeID(v)
	})
}

// UpdateAssigneeID sets the "assignee_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateAssigneeID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateAssigneeID()
	})
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (u *TicketUpsertOne) ClearAssigneeID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearAssigneeID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *TicketUpsertOne) SetRequestID(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateRequestID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRequestID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *TicketUpsertOne) SetUsageLogID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *TicketUpsertOne) AddUsageLogID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateUsageLogID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *TicketUpsertOne) ClearUsageLogID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearUsageLogID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *TicketUpsertOne) SetAPIKeyID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *TicketUpsertOne) AddAPIKeyID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateAPIKeyID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *TicketUpsertOne) ClearAPIKeyID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAPIKeyName sets the "api_key_name" field.
func (u *TicketUpsertOne) SetAPIKeyName(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetAPIKeyName(v)
	})
}

// UpdateAPIKeyName sets the "api_key_name" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateAPIKeyName() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateAPIKeyName()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *TicketUpsertOne) SetPaymentOrderID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *TicketUpsertOne) AddPaymentOrderID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdatePaymentOrderID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *TicketUpsertOne) ClearPaymentOrderID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetPaymentOrderNo sets the "payment_order_no" field.
func (u *TicketUpsertOne) SetPaymentOrderNo(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetPaymentOrderNo(v)
	})
}

// UpdatePaymentOrderNo sets the "payment_order_no" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdatePaymentOrderNo() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePaymentOrderNo()
	})
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *TicketUpsertOne) SetUserSubscriptionID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetUserSubscriptionID(v)
	})
}

// AddUserSubscriptionID adds v to the "user_subscription_id" field.
func (u *TicketUpsertOne) AddUserSubscriptionID(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddUserSubscriptionID(v)
	})
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateUserSubscriptionID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUserSubscriptionID()
	})
}

// ClearUserSubscriptionID clears the value of the "user_subscription_id" field.
func (u *TicketUpsertOne) ClearUserSubscriptionID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearUserSubscriptionID()
	})
}

// SetSubscriptionName sets the "subscription_name" field.
func (u *TicketUpsertOne) SetSubscriptionName(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetSubscriptionName(v)
	})
}

// UpdateSubscriptionName sets the "subscription_name" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateSubscriptionName() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateSubscriptionName()
	})
}

// SetLastPublicMessageAt sets the "last_public_message_at" field.
func (u *TicketUpsertOne) SetLastPublicMessageAt(v time.Time) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetLastPublicMessageAt(v)
	})
}

// UpdateLastPublicMessageAt sets the "last_public_message_at" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateLastPublicMessageAt() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateLastPublicMessageAt()
	})
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *TicketUpsertOne) SetLastActivityAt(v time.Time) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetLastActivityAt(v)
	})
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateLastActivityAt() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateLastActivityAt()
	})
}

// SetActionRequiredSince sets the "action_required_since" field.
func (u *TicketUpsertOne) SetActionRequiredSince(v time.Time) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetActionRequiredSince(v)
	})
}

// UpdateActionRequiredSince sets the "action_required_since" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateActionRequiredSince() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateActionRequiredSince()
	})
}

// ClearActionRequiredSince clears the value of the "action_required_since" field.
func (u *TicketUpsertOne) ClearActionRequiredSince() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearActionRequiredSince()
	})
}

// SetUserNotificationSeq sets the "user_notification_seq" field.
func (u *TicketUpsertOne) SetUserNotificationSeq(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetUserNotificationSeq(v)
	})
}

// AddUserNotificationSeq adds v to the "user_notification_seq" field.
func (u *TicketUpsertOne) AddUserNotificationSeq(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddUserNotificationSeq(v)
	})
}

// UpdateUserNotificationSeq sets the "user_notification_seq" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateUserNotificationSeq() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUserNotificationSeq()
	})
}

// SetUserLastReadSeq sets the "user_last_read_seq" field.
func (u *TicketUpsertOne) SetUserLastReadSeq(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetUserLastReadSeq(v)
	})
}

// AddUserLastReadSeq adds v to the "user_last_read_seq" field.
func (u *TicketUpsertOne) AddUserLastReadSeq(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddUserLastReadSeq(v)
	})
}

// UpdateUserLastReadSeq sets the "user_last_read_seq" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateUserLastReadSeq() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUserLastReadSeq()
	})
}

// SetResolvedAt sets the "resolved_at" field.
func (u *TicketUpsertOne) SetResolvedAt(v time.Time) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetResolvedAt(v)
	})
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateResolvedAt() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateResolvedAt()
	})
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *TicketUpsertOne) ClearResolvedAt() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearResolvedAt()
	})
}

// SetReopenDeadline sets the "reopen_deadline" field.
func (u *TicketUpsertOne) SetReopenDeadline(v time.Time) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetReopenDeadline(v)
	})
}

// UpdateReopenDeadline sets the "reopen_deadline" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateReopenDeadline() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateReopenDeadline()
	})
}

// ClearReopenDeadline clears the value of the "reopen_deadline" field.
func (u *TicketUpsertOne) ClearReopenDeadline() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearReopenDeadline()
	})
}

// SetClosedAt sets the "closed_at" field.
func (u *TicketUpsertOne) SetClosedAt(v time.Time) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetClosedAt(v)
	})
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateClosedAt() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateClosedAt()
	})
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *TicketUpsertOne) ClearClosedAt() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearClosedAt()
	})
}

// SetVersion sets the "version" field.
func (u *TicketUpsertOne) SetVersion(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *TicketUpsertOne) AddVersion(v int64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateVersion() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *TicketUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketCreateBulk is the builder for creating many Ticket entities in bulk.
type TicketCreateBulk struct {
	config
	err      error
	builders []*TicketCreate
	conflict []sql.ConflictOption
}

// Save creates the Ticket entities in the database.
func (_c *TicketCreateBulk) Save(ctx context.Context) ([]*Ticket, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ticket, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketCreateBulk) SaveX(ctx context.Context) []*Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ticket.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketUpsertBulk {
	_c.conflict = opts
	return &TicketUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketCreateBulk) OnConflictColumns(columns ...string) *TicketUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketUpsertBulk{
		create: _c,
	}
}

// TicketUpsertBulk is the builder for "upsert"-ing
// a bulk of Ticket nodes.
type TicketUpsertBulk struct {
	create *TicketCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketUpsertBulk) UpdateNewValues() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ticket.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketUpsertBulk) Ignore() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketUpsertBulk) DoNothing() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketCreateBulk.OnConflict
// documentation for more info.
func (u *TicketUpsertBulk) Update(set func(*TicketUpsert)) *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketUpsertBulk) SetUpdatedAt(v time.Time) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateUpdatedAt() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTicketNo sets the "ticket_no" field.
func (u *TicketUpsertBulk) SetTicketNo(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetTicketNo(v)
	})
}

// UpdateTicketNo sets the "ticket_no" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateTicketNo() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateTicketNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *TicketUpsertBulk) SetUserID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateUserID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *TicketUpsertBulk) ClearUserID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearUserID()
	})
}

// SetRequesterEmail sets the "requester_email" field.
func (u *TicketUpsertBulk) SetRequesterEmail(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetRequesterEmail(v)
	})
}

// UpdateRequesterEmail sets the "requester_email" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateRequesterEmail() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRequesterEmail()
	})
}

// SetRequesterUsername sets the "requester_username" field.
func (u *TicketUpsertBulk) SetRequesterUsername(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetRequesterUsername(v)
	})
}

// UpdateRequesterUsername sets the "requester_username" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateRequesterUsername() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRequesterUsername()
	})
}

// SetSubject sets the "subject" field.
func (u *TicketUpsertBulk) SetSubject(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateSubject() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateSubject()
	})
}

// SetCategory sets the "category" field.
func (u *TicketUpsertBulk) SetCategory(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateCategory() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateCategory()
	})
}

// SetImpact sets the "impact" field.
func (u *TicketUpsertBulk) SetImpact(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetImpact(v)
	})
}

// UpdateImpact sets the "impact" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateImpact() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateImpact()
	})
}

// SetPriority sets the "priority" field.
func (u *TicketUpsertBulk) SetPriority(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdatePriority() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePriority()
	})
}

// SetStatus sets the "status" field.
func (u *TicketUpsertBulk) SetStatus(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateStatus() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateStatus()
	})
}

// SetAssigneeID sets the "assignee_id" field.
func (u *TicketUpsertBulk) SetAssigneeID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetAssigneeID(v)
	})
}

// UpdateAssigneeID sets the "assignee_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateAssigneeID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateAssigneeID()
	})
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (u *TicketUpsertBulk) ClearAssigneeID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearAssigneeID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *TicketUpsertBulk) SetRequestID(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateRequestID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRequestID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *TicketUpsertBulk) SetUsageLogID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *TicketUpsertBulk) AddUsageLogID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateUsageLogID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *TicketUpsertBulk) ClearUsageLogID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearUsageLogID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *TicketUpsertBulk) SetAPIKeyID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *TicketUpsertBulk) AddAPIKeyID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateAPIKeyID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *TicketUpsertBulk) ClearAPIKeyID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAPIKeyName sets the "api_key_name" field.
func (u *TicketUpsertBulk) SetAPIKeyName(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetAPIKeyName(v)
	})
}

// UpdateAPIKeyName sets the "api_key_name" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateAPIKeyName() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateAPIKeyName()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *TicketUpsertBulk) SetPaymentOrderID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *TicketUpsertBulk) AddPaymentOrderID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdatePaymentOrderID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *TicketUpsertBulk) ClearPaymentOrderID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetPaymentOrderNo sets the "payment_order_no" field.
func (u *TicketUpsertBulk) SetPaymentOrderNo(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetPaymentOrderNo(v)
	})
}

// UpdatePaymentOrderNo sets the "payment_order_no" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdatePaymentOrderNo() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePaymentOrderNo()
	})
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *TicketUpsertBulk) SetUserSubscriptionID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetUserSubscriptionID(v)
	})
}

// AddUserSubscriptionID adds v to the "user_subscription_id" field.
func (u *TicketUpsertBulk) AddUserSubscriptionID(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddUserSubscriptionID(v)
	})
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateUserSubscriptionID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUserSubscriptionID()
	})
}

// ClearUserSubscriptionID clears the value of the "user_subscription_id" field.
func (u *TicketUpsertBulk) ClearUserSubscriptionID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearUserSubscriptionID()
	})
}

// SetSubscriptionName sets the "subscription_name" field.
func (u *TicketUpsertBulk) SetSubscriptionName(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetSubscriptionName(v)
	})
}

// UpdateSubscriptionName sets the "subscription_name" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateSubscriptionName() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateSubscriptionName()
	})
}

// SetLastPublicMessageAt sets the "last_public_message_at" field.
func (u *TicketUpsertBulk) SetLastPublicMessageAt(v time.Time) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetLastPublicMessageAt(v)
	})
}

// UpdateLastPublicMessageAt sets the "last_public_message_at" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateLastPublicMessageAt() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateLastPublicMessageAt()
	})
}

// SetLastActivityAt sets the "last_activity_at" field.
func (u *TicketUpsertBulk) SetLastActivityAt(v time.Time) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetLastActivityAt(v)
	})
}

// UpdateLastActivityAt sets the "last_activity_at" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateLastActivityAt() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateLastActivityAt()
	})
}

// SetActionRequiredSince sets the "action_required_since" field.
func (u *TicketUpsertBulk) SetActionRequiredSince(v time.Time) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetActionRequiredSince(v)
	})
}

// UpdateActionRequiredSince sets the "action_required_since" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateActionRequiredSince() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateActionRequiredSince()
	})
}

// ClearActionRequiredSince clears the value of the "action_required_since" field.
func (u *TicketUpsertBulk) ClearActionRequiredSince() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearActionRequiredSince()
	})
}

// SetUserNotificationSeq sets the "user_notification_seq" field.
func (u *TicketUpsertBulk) SetUserNotificationSeq(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetUserNotificationSeq(v)
	})
}

// AddUserNotificationSeq adds v to the "user_notification_seq" field.
func (u *TicketUpsertBulk) AddUserNotificationSeq(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddUserNotificationSeq(v)
	})
}

// UpdateUserNotificationSeq sets the "user_notification_seq" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateUserNotificationSeq() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUserNotificationSeq()
	})
}

// SetUserLastReadSeq sets the "user_last_read_seq" field.
func (u *TicketUpsertBulk) SetUserLastReadSeq(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetUserLastReadSeq(v)
	})
}

// AddUserLastReadSeq adds v to the "user_last_read_seq" field.
func (u *TicketUpsertBulk) AddUserLastReadSeq(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddUserLastReadSeq(v)
	})
}

// UpdateUserLastReadSeq sets the "user_last_read_seq" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateUserLastReadSeq() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUserLastReadSeq()
	})
}

// SetResolvedAt sets the "resolved_at" field.
func (u *TicketUpsertBulk) SetResolvedAt(v time.Time) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetResolvedAt(v)
	})
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateResolvedAt() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateResolvedAt()
	})
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *TicketUpsertBulk) ClearResolvedAt() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearResolvedAt()
	})
}

// SetReopenDeadline sets the "reopen_deadline" field.
func (u *TicketUpsertBulk) SetReopenDeadline(v time.Time) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetReopenDeadline(v)
	})
}

// UpdateReopenDeadline sets the "reopen_deadline" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateReopenDeadline() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateReopenDeadline()
	})
}

// ClearReopenDeadline clears the value of the "reopen_deadline" field.
func (u *TicketUpsertBulk) ClearReopenDeadline() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearReopenDeadline()
	})
}

// SetClosedAt sets the "closed_at" field.
func (u *TicketUpsertBulk) SetClosedAt(v time.Time) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetClosedAt(v)
	})
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateClosedAt() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateClosedAt()
	})
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *TicketUpsertBulk) ClearClosedAt() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearClosedAt()
	})
}

// SetVersion sets the "version" field.
func (u *TicketUpsertBulk) SetVersion(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *TicketUpsertBulk) AddVersion(v int64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateVersion() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *TicketUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
