// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ticket"
	"github.com/Wei-Shaw/sub2api/ent/ticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TicketMessageCreate is the builder for creating a TicketMessage entity.
type TicketMessageCreate struct {
	config
	mutation *TicketMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTicketID sets the "ticket_id" field.
func (_c *TicketMessageCreate) SetTicketID(v int64) *TicketMessageCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *TicketMessageCreate) SetAuthorID(v int64) *TicketMessageCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_c *TicketMessageCreate) SetNillableAuthorID(v *int64) *TicketMessageCreate {
	if v != nil {
		_c.SetAuthorID(*v)
	}
	return _c
}

// SetAuthorRole sets the "author_role" field.
func (_c *TicketMessageCreate) SetAuthorRole(v string) *TicketMessageCreate {
	_c.mutation.SetAuthorRole(v)
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *TicketMessageCreate) SetVisibility(v string) *TicketMessageCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetAuthorName sets the "author_name" field.
func (_c *TicketMessageCreate) SetAuthorName(v string) *TicketMessageCreate {
	_c.mutation.SetAuthorName(v)
	return _c
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_c *TicketMessageCreate) SetNillableAuthorName(v *string) *TicketMessageCreate {
	if v != nil {
		_c.SetAuthorName(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *TicketMessageCreate) SetBody(v string) *TicketMessageCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketMessageCreate) SetCreatedAt(v time.Time) *TicketMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketMessageCreate) SetNillableCreatedAt(v *time.Time) *TicketMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTicket sets the "ticket" edge to the Ticket entity.
func (_c *TicketMessageCreate) SetTicket(v *Ticket) *TicketMessageCreate {
	return _c.SetTicketID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *TicketMessageCreate) SetAuthor(v *User) *TicketMessageCreate {
	return _c.SetAuthorID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the TicketAttachment entity by IDs.
func (_c *TicketMessageCreate) AddAttachmentIDs(ids ...int64) *TicketMessageCreate {
	_c.mutation.AddAttachmentIDs(ids...)
	return _c
}

// AddAttachments adds the "attachments" edges to the TicketAttachment entity.
func (_c *TicketMessageCreate) AddAttachments(v ...*TicketAttachment) *TicketMessageCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttachmentIDs(ids...)
}

// Mutation returns the TicketMessageMutation object of the builder.
func (_c *TicketMessageCreate) Mutation() *TicketMessageMutation {
	return _c.mutation
}

// Save creates the TicketMessage in the database.
func (_c *TicketMessageCreate) Save(ctx context.Context) (*TicketMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketMessageCreate) SaveX(ctx context.Context) *TicketMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketMessageCreate) defaults() {
	if _, ok := _c.mutation.AuthorName(); !ok {
		v := ticketmessage.DefaultAuthorName
		_c.mutation.SetAuthorName(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticketmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketMessageCreate) check() error {
	if _, ok := _c.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "TicketMessage.ticket_id"`)}
	}
	if _, ok := _c.mutation.AuthorRole(); !ok {
		return &ValidationError{Name: "author_role", err: errors.New(`ent: missing required field "TicketMessage.author_role"`)}
	}
	if v, ok := _c.mutation.AuthorRole(); ok {
		if err := ticketmessage.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.author_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "TicketMessage.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := ticketmessage.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorName(); !ok {
		return &ValidationError{Name: "author_name", err: errors.New(`ent: missing required field "TicketMessage.author_name"`)}
	}
	if v, ok := _c.mutation.AuthorName(); ok {
		if err := ticketmessage.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.author_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "TicketMessage.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := ticketmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TicketMessage.created_at"`)}
	}
	if len(_c.mutation.TicketIDs()) == 0 {
		return &ValidationError{Name: "ticket", err: errors.New(`ent: missing required edge "TicketMessage.ticket"`)}
	}
	return nil
}

func (_c *TicketMessageCreate) sqlSave(ctx context.Context) (*TicketMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketMessageCreate) createSpec() (*TicketMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketmessage.Table, sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AuthorRole(); ok {
		_spec.SetField(ticketmessage.FieldAuthorRole, field.TypeString, value)
		_node.AuthorRole = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(ticketmessage.FieldVisibility, field.TypeString, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.AuthorName(); ok {
		_spec.SetField(ticketmessage.FieldAuthorName, field.TypeString, value)
		_node.AuthorName = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(ticketmessage.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticketmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.TicketTable,
			Columns: []string{ticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TicketID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ticketmessage.AuthorTable,
			Columns: []string{ticketmessage.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticketmessage.AttachmentsTable,
			Columns: []string{ticketmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketMessage.Create().
//		SetTicketID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketMessageUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketMessageCreate) OnConflict(opts ...sql.ConflictOption) *TicketMessageUpsertOne {
	_c.conflict = opts
	return &TicketMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketMessageCreate) OnConflictColumns(columns ...string) *TicketMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketMessageUpsertOne{
		create: _c,
	}
}

type (
	// TicketMessageUpsertOne is the builder for "upsert"-ing
	//  one TicketMessage node.
	TicketMessageUpsertOne struct {
		create *TicketMessageCreate
	}

	// TicketMessageUpsert is the "OnConflict" setter.
	TicketMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetTicketID sets the "ticket_id" field.
func (u *TicketMessageUpsert) SetTicketID(v int64) *TicketMessageUpsert {
	u.Set(ticketmessage.FieldTicketID, v)
	return u
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketMessageUpsert) UpdateTicketID() *TicketMessageUpsert {
	u.SetExcluded(ticketmessage.FieldTicketID)
	return u
}

// SetAuthorID sets the "author_id" field.
func (u *TicketMessageUpsert) SetAuthorID(v int64) *TicketMessageUpsert {
	u.Set(ticketmessage.FieldAuthorID, v)
	return u
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *TicketMessageUpsert) UpdateAuthorID() *TicketMessageUpsert {
	u.SetExcluded(ticketmessage.FieldAuthorID)
	return u
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *TicketMessageUpsert) ClearAuthorID() *TicketMessageUpsert {
	u.SetNull(ticketmessage.FieldAuthorID)
	return u
}

// SetAuthorRole sets the "author_role" field.
func (u *TicketMessageUpsert) SetAuthorRole(v string) *TicketMessageUpsert {
	u.Set(ticketmessage.FieldAuthorRole, v)
	return u
}

// UpdateAuthorRole sets the "author_role" field to the value that was provided on create.
func (u *TicketMessageUpsert) UpdateAuthorRole() *TicketMessageUpsert {
	u.SetExcluded(ticketmessage.FieldAuthorRole)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *TicketMessageUpsert) SetVisibility(v string) *TicketMessageUpsert {
	u.Set(ticketmessage.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketMessageUpsert) UpdateVisibility() *TicketMessageUpsert {
	u.SetExcluded(ticketmessage.FieldVisibility)
	return u
}

// SetAuthorName sets the "author_name" field.
func (u *TicketMessageUpsert) SetAuthorName(v string) *TicketMessageUpsert {
	u.Set(ticketmessage.FieldAuthorName, v)
	return u
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *TicketMessageUpsert) UpdateAuthorName() *TicketMessageUpsert {
	u.SetExcluded(ticketmessage.FieldAuthorName)
	return u
}

// SetBody sets the "body" field.
func (u *TicketMessageUpsert) SetBody(v string) *TicketMessageUpsert {
	u.Set(ticketmessage.FieldBody, v)
	return u
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *TicketMessageUpsert) UpdateBody() *TicketMessageUpsert {
	u.SetExcluded(ticketmessage.FieldBody)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TicketMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketMessageUpsertOne) UpdateNewValues() *TicketMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ticketmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketMessageUpsertOne) Ignore() *TicketMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketMessageUpsertOne) DoNothing() *TicketMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketMessageCreate.OnConflict
// documentation for more info.
func (u *TicketMessageUpsertOne) Update(set func(*TicketMessageUpsert)) *TicketMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketMessageUpsertOne) SetTicketID(v int64) *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketMessageUpsertOne) UpdateTicketID() *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateTicketID()
	})
}

// SetAuthorID sets the "author_id" field.
func (u *TicketMessageUpsertOne) SetAuthorID(v int64) *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *TicketMessageUpsertOne) UpdateAuthorID() *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateAuthorID()
	})
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *TicketMessageUpsertOne) ClearAuthorID() *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.ClearAuthorID()
	})
}

// SetAuthorRole sets the "author_role" field.
func (u *TicketMessageUpsertOne) SetAuthorRole(v string) *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetAuthorRole(v)
	})
}

// UpdateAuthorRole sets the "author_role" field to the value that was provided on create.
func (u *TicketMessageUpsertOne) UpdateAuthorRole() *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateAuthorRole()
	})
}

// SetVisibility sets the "visibility" field.
func (u *TicketMessageUpsertOne) SetVisibility(v string) *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketMessageUpsertOne) UpdateVisibility() *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateVisibility()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *TicketMessageUpsertOne) SetAuthorName(v string) *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *TicketMessageUpsertOne) UpdateAuthorName() *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateAuthorName()
	})
}

// SetBody sets the "body" field.
func (u *TicketMessageUpsertOne) SetBody(v string) *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *TicketMessageUpsertOne) UpdateBody() *TicketMessageUpsertOne {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateBody()
	})
}

// Exec executes the query.
func (u *TicketMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketMessageCreateBulk is the builder for creating many TicketMessage entities in bulk.
type TicketMessageCreateBulk struct {
	config
	err      error
	builders []*TicketMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketMessage entities in the database.
func (_c *TicketMessageCreateBulk) Save(ctx context.Context) ([]*TicketMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketMessageCreateBulk) SaveX(ctx context.Context) []*TicketMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketMessageUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketMessageUpsertBulk {
	_c.conflict = opts
	return &TicketMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketMessageCreateBulk) OnConflictColumns(columns ...string) *TicketMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketMessageUpsertBulk{
		create: _c,
	}
}

// TicketMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketMessage nodes.
type TicketMessageUpsertBulk struct {
	create *TicketMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TicketMessageUpsertBulk) UpdateNewValues() *TicketMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ticketmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketMessageUpsertBulk) Ignore() *TicketMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketMessageUpsertBulk) DoNothing() *TicketMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketMessageCreateBulk.OnConflict
// documentation for more info.
func (u *TicketMessageUpsertBulk) Update(set func(*TicketMessageUpsert)) *TicketMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketMessageUpsertBulk) SetTicketID(v int64) *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketMessageUpsertBulk) UpdateTicketID() *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateTicketID()
	})
}

// SetAuthorID sets the "author_id" field.
func (u *TicketMessageUpsertBulk) SetAuthorID(v int64) *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *TicketMessageUpsertBulk) UpdateAuthorID() *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateAuthorID()
	})
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *TicketMessageUpsertBulk) ClearAuthorID() *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.ClearAuthorID()
	})
}

// SetAuthorRole sets the "author_role" field.
func (u *TicketMessageUpsertBulk) SetAuthorRole(v string) *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetAuthorRole(v)
	})
}

// UpdateAuthorRole sets the "author_role" field to the value that was provided on create.
func (u *TicketMessageUpsertBulk) UpdateAuthorRole() *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateAuthorRole()
	})
}

// SetVisibility sets the "visibility" field.
func (u *TicketMessageUpsertBulk) SetVisibility(v string) *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *TicketMessageUpsertBulk) UpdateVisibility() *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateVisibility()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *TicketMessageUpsertBulk) SetAuthorName(v string) *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *TicketMessageUpsertBulk) UpdateAuthorName() *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateAuthorName()
	})
}

// SetBody sets the "body" field.
func (u *TicketMessageUpsertBulk) SetBody(v string) *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *TicketMessageUpsertBulk) UpdateBody() *TicketMessageUpsertBulk {
	return u.Update(func(s *TicketMessageUpsert) {
		s.UpdateBody()
	})
}

// Exec executes the query.
func (u *TicketMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
