// Code generated by ent, DO NOT EDIT.

package ticketevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ticketevent type in the database.
	Label = "ticket_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTicketID holds the string denoting the ticket_id field in the database.
	FieldTicketID = "ticket_id"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// FieldActorRole holds the string denoting the actor_role field in the database.
	FieldActorRole = "actor_role"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldFromStatus holds the string denoting the from_status field in the database.
	FieldFromStatus = "from_status"
	// FieldToStatus holds the string denoting the to_status field in the database.
	FieldToStatus = "to_status"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldVisibility holds the string denoting the visibility field in the database.
	FieldVisibility = "visibility"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTicket holds the string denoting the ticket edge name in mutations.
	EdgeTicket = "ticket"
	// EdgeActor holds the string denoting the actor edge name in mutations.
	EdgeActor = "actor"
	// Table holds the table name of the ticketevent in the database.
	Table = "ticket_events"
	// TicketTable is the table that holds the ticket relation/edge.
	TicketTable = "ticket_events"
	// TicketInverseTable is the table name for the Ticket entity.
	// It exists in this package in order to avoid circular dependency with the "ticket" package.
	TicketInverseTable = "tickets"
	// TicketColumn is the table column denoting the ticket relation/edge.
	TicketColumn = "ticket_id"
	// ActorTable is the table that holds the actor relation/edge.
	ActorTable = "ticket_events"
	// ActorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ActorInverseTable = "users"
	// ActorColumn is the table column denoting the actor relation/edge.
	ActorColumn = "actor_id"
)

// Columns holds all SQL columns for ticketevent fields.
var Columns = []string{
	FieldID,
	FieldTicketID,
	FieldActorID,
	FieldActorRole,
	FieldEventType,
	FieldFromStatus,
	FieldToStatus,
	FieldPayload,
	FieldVisibility,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActorRoleValidator is a validator for the "actor_role" field. It is called by the builders before save.
	ActorRoleValidator func(string) error
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// FromStatusValidator is a validator for the "from_status" field. It is called by the builders before save.
	FromStatusValidator func(string) error
	// ToStatusValidator is a validator for the "to_status" field. It is called by the builders before save.
	ToStatusValidator func(string) error
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload func() map[string]interface{}
	// VisibilityValidator is a validator for the "visibility" field. It is called by the builders before save.
	VisibilityValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the TicketEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTicketID orders the results by the ticket_id field.
func ByTicketID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketID, opts...).ToFunc()
}

// ByActorID orders the results by the actor_id field.
func ByActorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorID, opts...).ToFunc()
}

// ByActorRole orders the results by the actor_role field.
func ByActorRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorRole, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByFromStatus orders the results by the from_status field.
func ByFromStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromStatus, opts...).ToFunc()
}

// ByToStatus orders the results by the to_status field.
func ByToStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToStatus, opts...).ToFunc()
}

// ByVisibility orders the results by the visibility field.
func ByVisibility(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibility, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTicketField orders the results by ticket field.
func ByTicketField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTicketStep(), sql.OrderByField(field, opts...))
	}
}

// ByActorField orders the results by actor field.
func ByActorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActorStep(), sql.OrderByField(field, opts...))
	}
}
func newTicketStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TicketInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
	)
}
func newActorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActorTable, ActorColumn),
	)
}
