// Code generated by ent, DO NOT EDIT.

package ticketattachment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldID, id))
}

// UploadToken applies equality check predicate on the "upload_token" field. It's identical to UploadTokenEQ.
func UploadToken(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldUploadToken, v))
}

// UploadedBy applies equality check predicate on the "uploaded_by" field. It's identical to UploadedByEQ.
func UploadedBy(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldUploadedBy, v))
}

// UploaderRole applies equality check predicate on the "uploader_role" field. It's identical to UploaderRoleEQ.
func UploaderRole(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldUploaderRole, v))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldTicketID, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldMessageID, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldState, v))
}

// StorageProvider applies equality check predicate on the "storage_provider" field. It's identical to StorageProviderEQ.
func StorageProvider(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldStorageProvider, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldObjectKey, v))
}

// OriginalName applies equality check predicate on the "original_name" field. It's identical to OriginalNameEQ.
func OriginalName(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldOriginalName, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldContentType, v))
}

// ByteSize applies equality check predicate on the "byte_size" field. It's identical to ByteSizeEQ.
func ByteSize(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldByteSize, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldSha256, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// UploadTokenEQ applies the EQ predicate on the "upload_token" field.
func UploadTokenEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldUploadToken, v))
}

// UploadTokenNEQ applies the NEQ predicate on the "upload_token" field.
func UploadTokenNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldUploadToken, v))
}

// UploadTokenIn applies the In predicate on the "upload_token" field.
func UploadTokenIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldUploadToken, vs...))
}

// UploadTokenNotIn applies the NotIn predicate on the "upload_token" field.
func UploadTokenNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldUploadToken, vs...))
}

// UploadTokenGT applies the GT predicate on the "upload_token" field.
func UploadTokenGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldUploadToken, v))
}

// UploadTokenGTE applies the GTE predicate on the "upload_token" field.
func UploadTokenGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldUploadToken, v))
}

// UploadTokenLT applies the LT predicate on the "upload_token" field.
func UploadTokenLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldUploadToken, v))
}

// UploadTokenLTE applies the LTE predicate on the "upload_token" field.
func UploadTokenLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldUploadToken, v))
}

// UploadTokenContains applies the Contains predicate on the "upload_token" field.
func UploadTokenContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldUploadToken, v))
}

// UploadTokenHasPrefix applies the HasPrefix predicate on the "upload_token" field.
func UploadTokenHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldUploadToken, v))
}

// UploadTokenHasSuffix applies the HasSuffix predicate on the "upload_token" field.
func UploadTokenHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldUploadToken, v))
}

// UploadTokenEqualFold applies the EqualFold predicate on the "upload_token" field.
func UploadTokenEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldUploadToken, v))
}

// UploadTokenContainsFold applies the ContainsFold predicate on the "upload_token" field.
func UploadTokenContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldUploadToken, v))
}

// UploadedByEQ applies the EQ predicate on the "uploaded_by" field.
func UploadedByEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldUploadedBy, v))
}

// UploadedByNEQ applies the NEQ predicate on the "uploaded_by" field.
func UploadedByNEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldUploadedBy, v))
}

// UploadedByIn applies the In predicate on the "uploaded_by" field.
func UploadedByIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldUploadedBy, vs...))
}

// UploadedByNotIn applies the NotIn predicate on the "uploaded_by" field.
func UploadedByNotIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldUploadedBy, vs...))
}

// UploadedByIsNil applies the IsNil predicate on the "uploaded_by" field.
func UploadedByIsNil() predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIsNull(FieldUploadedBy))
}

// UploadedByNotNil applies the NotNil predicate on the "uploaded_by" field.
func UploadedByNotNil() predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotNull(FieldUploadedBy))
}

// UploaderRoleEQ applies the EQ predicate on the "uploader_role" field.
func UploaderRoleEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldUploaderRole, v))
}

// UploaderRoleNEQ applies the NEQ predicate on the "uploader_role" field.
func UploaderRoleNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldUploaderRole, v))
}

// UploaderRoleIn applies the In predicate on the "uploader_role" field.
func UploaderRoleIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldUploaderRole, vs...))
}

// UploaderRoleNotIn applies the NotIn predicate on the "uploader_role" field.
func UploaderRoleNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldUploaderRole, vs...))
}

// UploaderRoleGT applies the GT predicate on the "uploader_role" field.
func UploaderRoleGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldUploaderRole, v))
}

// UploaderRoleGTE applies the GTE predicate on the "uploader_role" field.
func UploaderRoleGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldUploaderRole, v))
}

// UploaderRoleLT applies the LT predicate on the "uploader_role" field.
func UploaderRoleLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldUploaderRole, v))
}

// UploaderRoleLTE applies the LTE predicate on the "uploader_role" field.
func UploaderRoleLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldUploaderRole, v))
}

// UploaderRoleContains applies the Contains predicate on the "uploader_role" field.
func UploaderRoleContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldUploaderRole, v))
}

// UploaderRoleHasPrefix applies the HasPrefix predicate on the "uploader_role" field.
func UploaderRoleHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldUploaderRole, v))
}

// UploaderRoleHasSuffix applies the HasSuffix predicate on the "uploader_role" field.
func UploaderRoleHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldUploaderRole, v))
}

// UploaderRoleEqualFold applies the EqualFold predicate on the "uploader_role" field.
func UploaderRoleEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldUploaderRole, v))
}

// UploaderRoleContainsFold applies the ContainsFold predicate on the "uploader_role" field.
func UploaderRoleContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldUploaderRole, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldTicketID, vs...))
}

// TicketIDIsNil applies the IsNil predicate on the "ticket_id" field.
func TicketIDIsNil() predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIsNull(FieldTicketID))
}

// TicketIDNotNil applies the NotNil predicate on the "ticket_id" field.
func TicketIDNotNil() predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotNull(FieldTicketID))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDIsNil applies the IsNil predicate on the "message_id" field.
func MessageIDIsNil() predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIsNull(FieldMessageID))
}

// MessageIDNotNil applies the NotNil predicate on the "message_id" field.
func MessageIDNotNil() predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotNull(FieldMessageID))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldState, v))
}

// StorageProviderEQ applies the EQ predicate on the "storage_provider" field.
func StorageProviderEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldStorageProvider, v))
}

// StorageProviderNEQ applies the NEQ predicate on the "storage_provider" field.
func StorageProviderNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldStorageProvider, v))
}

// StorageProviderIn applies the In predicate on the "storage_provider" field.
func StorageProviderIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldStorageProvider, vs...))
}

// StorageProviderNotIn applies the NotIn predicate on the "storage_provider" field.
func StorageProviderNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldStorageProvider, vs...))
}

// StorageProviderGT applies the GT predicate on the "storage_provider" field.
func StorageProviderGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldStorageProvider, v))
}

// StorageProviderGTE applies the GTE predicate on the "storage_provider" field.
func StorageProviderGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldStorageProvider, v))
}

// StorageProviderLT applies the LT predicate on the "storage_provider" field.
func StorageProviderLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldStorageProvider, v))
}

// StorageProviderLTE applies the LTE predicate on the "storage_provider" field.
func StorageProviderLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldStorageProvider, v))
}

// StorageProviderContains applies the Contains predicate on the "storage_provider" field.
func StorageProviderContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldStorageProvider, v))
}

// StorageProviderHasPrefix applies the HasPrefix predicate on the "storage_provider" field.
func StorageProviderHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldStorageProvider, v))
}

// StorageProviderHasSuffix applies the HasSuffix predicate on the "storage_provider" field.
func StorageProviderHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldStorageProvider, v))
}

// StorageProviderEqualFold applies the EqualFold predicate on the "storage_provider" field.
func StorageProviderEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldStorageProvider, v))
}

// StorageProviderContainsFold applies the ContainsFold predicate on the "storage_provider" field.
func StorageProviderContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldStorageProvider, v))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldObjectKey, v))
}

// OriginalNameEQ applies the EQ predicate on the "original_name" field.
func OriginalNameEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldOriginalName, v))
}

// OriginalNameNEQ applies the NEQ predicate on the "original_name" field.
func OriginalNameNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldOriginalName, v))
}

// OriginalNameIn applies the In predicate on the "original_name" field.
func OriginalNameIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldOriginalName, vs...))
}

// OriginalNameNotIn applies the NotIn predicate on the "original_name" field.
func OriginalNameNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldOriginalName, vs...))
}

// OriginalNameGT applies the GT predicate on the "original_name" field.
func OriginalNameGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldOriginalName, v))
}

// OriginalNameGTE applies the GTE predicate on the "original_name" field.
func OriginalNameGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldOriginalName, v))
}

// OriginalNameLT applies the LT predicate on the "original_name" field.
func OriginalNameLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldOriginalName, v))
}

// OriginalNameLTE applies the LTE predicate on the "original_name" field.
func OriginalNameLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldOriginalName, v))
}

// OriginalNameContains applies the Contains predicate on the "original_name" field.
func OriginalNameContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldOriginalName, v))
}

// OriginalNameHasPrefix applies the HasPrefix predicate on the "original_name" field.
func OriginalNameHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldOriginalName, v))
}

// OriginalNameHasSuffix applies the HasSuffix predicate on the "original_name" field.
func OriginalNameHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldOriginalName, v))
}

// OriginalNameEqualFold applies the EqualFold predicate on the "original_name" field.
func OriginalNameEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldOriginalName, v))
}

// OriginalNameContainsFold applies the ContainsFold predicate on the "original_name" field.
func OriginalNameContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldOriginalName, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldContentType, v))
}

// ByteSizeEQ applies the EQ predicate on the "byte_size" field.
func ByteSizeEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldByteSize, v))
}

// ByteSizeNEQ applies the NEQ predicate on the "byte_size" field.
func ByteSizeNEQ(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldByteSize, v))
}

// ByteSizeIn applies the In predicate on the "byte_size" field.
func ByteSizeIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldByteSize, vs...))
}

// ByteSizeNotIn applies the NotIn predicate on the "byte_size" field.
func ByteSizeNotIn(vs ...int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldByteSize, vs...))
}

// ByteSizeGT applies the GT predicate on the "byte_size" field.
func ByteSizeGT(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldByteSize, v))
}

// ByteSizeGTE applies the GTE predicate on the "byte_size" field.
func ByteSizeGTE(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldByteSize, v))
}

// ByteSizeLT applies the LT predicate on the "byte_size" field.
func ByteSizeLT(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldByteSize, v))
}

// ByteSizeLTE applies the LTE predicate on the "byte_size" field.
func ByteSizeLTE(v int64) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldByteSize, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldContainsFold(FieldSha256, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUploader applies the HasEdge predicate on the "uploader" edge.
func HasUploader() predicate.TicketAttachment {
	return predicate.TicketAttachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UploaderTable, UploaderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploaderWith applies the HasEdge predicate on the "uploader" edge with a given conditions (other predicates).
func HasUploaderWith(preds ...predicate.User) predicate.TicketAttachment {
	return predicate.TicketAttachment(func(s *sql.Selector) {
		step := newUploaderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TicketAttachment {
	return predicate.TicketAttachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TicketAttachment {
	return predicate.TicketAttachment(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.TicketAttachment {
	return predicate.TicketAttachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.TicketMessage) predicate.TicketAttachment {
	return predicate.TicketAttachment(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketAttachment) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketAttachment) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketAttachment) predicate.TicketAttachment {
	return predicate.TicketAttachment(sql.NotPredicates(p))
}
